[font]
normal = { family = "FantasqueSansM Nerd Font Mono Penguin", style = "Regular" }
bold = { family = "FantasqueSansM Nerd Font Mono Penguin", style = "Bold" }
italic = { family = "FantasqueSansM Nerd Font Mono Penguin", style = "Italic" }
bold_italic = { family = "FantasqueSansM Nerd Font Mono Penguin", style = "Bold Italic" }
size = 20
# Penguin "🐧", iIlL => 0Oo

[terminal]
shell = "/opt/homebrew/bin/tmux"

[window]
option_as_alt = "Both"
