[Source-applicationVersion]
dataSourceCommonSettings\activeState=true

[Source-compiler]
dataSourceCommonSettings\activeState=true

[Source-opengl]
dataSourceCommonSettings\activeState=true

[Source-panelCount]
dataSourceCommonSettings\activeState=true

[Source-platform]
dataSourceCommonSettings\activeState=true

[Source-qpa]
dataSourceCommonSettings\activeState=true

[Source-qtVersion]
dataSourceCommonSettings\activeState=true

[Source-screens]
dataSourceCommonSettings\activeState=true

[Source-usageTime]
dataSourceCommonSettings\activeState=true

[UserFeedback]
ApplicationStartCount=1372
ApplicationTime=6893191
LastSubmission=@DateTime(\0\0\0\x10\0\0\0\0\0\0%\x8bn\x3\x97*\x1d\0)
StatisticsCollectionMode=DetailedUsageStatistics
