-- Fix dapui colors
vim.cmd("highlight! default link DapUIStoppedThread Thread")
vim.cmd("highlight! default link DapUIThread Thread")

vim.cmd("highlight! default link DapUINormal Normal")
vim.cmd("highlight! default link DapUINormalNC NormalNC")
vim.cmd("highlight! default link DapUIVariable Normal")
vim.cmd("highlight! default link DapUIValue Normal")
vim.cmd("highlight! default link DapUISource Source")
vim.cmd("highlight! default link DapUIScope Type")
vim.cmd("highlight! default link DapUIType Type")
vim.cmd("highlight! default link DapUIModifiedValue Identifier")
vim.cmd("highlight! default link DapUIDecoration Comment")
vim.cmd("highlight! default link DapUIWatchesEmpty Comment")
vim.cmd("highlight! default link DapUIWatchesValue Identifier")
vim.cmd("highlight! default link DapUIWatchesError Error")

vim.cmd("highlight! default link DapUIStop Statement")
vim.cmd("highlight! default link DapUIStopNC DapUIStop")
vim.cmd("highlight! default link DapUIStepOver Statement")
vim.cmd("highlight! default link DapUIStepOverNC DapUIStepOver")
vim.cmd("highlight! default link DapUIStepInto Statement")
vim.cmd("highlight! default link DapUIStepIntoNC DapUIStepInto")
vim.cmd("highlight! default link DapUIStepBack Statement")
vim.cmd("highlight! default link DapUIStepBackNC DapUIStepBack")
vim.cmd("highlight! default link DapUIStepOut Statement")
vim.cmd("highlight! default link DapUIStepOutNC DapUIStepOut")
vim.cmd("highlight! default link DapUIPlayPause Statement")
vim.cmd("highlight! default link DapUIPlayPauseNC DapUIPlayPause")
vim.cmd("highlight! default link DapUIRestart Statement")
vim.cmd("highlight! default link DapUIRestartNC DapUIRestart")
vim.cmd("highlight! default link DapUIUnavailable Statement")
vim.cmd("highlight! default link DapUIUnavailableNC DapUIUnavailable")

vim.cmd("highlight! default link DapUILineNumber LineNr")
vim.cmd("highlight! default link DapUIFrameName Title")
vim.cmd("highlight! default link DapUICurrentFrameName Title")
vim.cmd("highlight! default link DapUIWinSelect Statement")
vim.cmd("highlight! default link DapUIFloatBorder NormalFloat")
vim.cmd("highlight! default link DapUIEndofBuffer EndOfBuffer")

vim.cmd("highlight! default link DapUIBreakpointsPath Comment")
vim.cmd("highlight! default link DapUIBreakpointsInfo Comment")
vim.cmd("highlight! default link DapUIBreakpointsCurrentLine CursorLine")
vim.cmd("highlight! default link DapUIBreakpointsDisabledLine Comment")
vim.cmd("highlight! default link DapUIBreakpointsLine DapUIBreakpointsLine")
