XDG_DATA_HOME=$HOME/.local/share
XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_STATE_HOME=$HOME/.local/state
LESSHISTFILE=$HOME/.local/state/less/history
GNUPGHOME=$HOME/.local/share/gnupg
CARGO_HOME=$HOME/.local/share/cargo
RUSTUP_HOME=$HOME/.local/share/rustup
ERRFILE=$HOME/.cache/X11/xsession-errors
CUDA_CACHE_PATH=$HOME/.cache/nv
NPM_CONFIG_INIT_MODULE=$HOME/.config/npm/config/npm-init.js
NPM_CONFIG_CACHE=$HOME/.cache/npm
NPM_CONFIG_TMP=/run/user/$UID/npm
PYTHON_HISTORY=$HOME/.local/share/python_history
WINEPREFIX=$HOME/.local/share/wine
DOCKER_CONFIG=$HOME/.config/docker
DOTNET_CLI_HOME=$HOME/.local/share/dotnet
_JAVA_OPTIONS=-Djava.util.prefs.userRoot=$HOME/.config/java
