[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\f/home/rad1an)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc3\0\0\0\x2\0\0\a}\0\0\x3\xfd\0\0\x3\xc5\0\0\0\x1e\0\0\a{\0\0\x3\xf9\0\0\0\0\x2\0\0\0\a\x80\0\0\x3\xc3\0\0\0\x1e\0\0\a}\0\0\x3\xfd)

[Epanel]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\xc0\0\0\0\0\0\0\x3\xfc\0\0\x2\a\0\0\x1\xc2\0\0\0\x1c\0\0\x3\xfa\0\0\x2\x3\0\0\0\0\0\0\0\0\a\x80\0\0\x1\xc2\0\0\0\x1c\0\0\x3\xfa\0\0\x2\x3)

[FullScreen]
pos=@Point(560 1012)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(955 902)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///run/user/1000/doc/636150c/parkour0.mp4, file:///run/user/1000/doc/2c8e3672/run0.mp4, file:///run/user/1000/doc/58c9aa33/untitled.mp4, file:///run/user/1000/doc/64fa0eea/2025_06_06_10_16_17.mp4, file:///run/user/1000/doc/3914fe6b/2025_06_06_00_04_46.mp4, file:///home/rad1an/test.mp4
times=0, 0, 32650, 0, 0, 0
