settings:
  log: {}
  metadata:
    last_update: ''
    update_interval: 48
  search:
    match_all: false
    newest_only: false
  show updates at startup: true
view:
  filter: to_update
  show: groups
