# airscan-discover
# Autogenerated from man page /usr/share/man/man1/airscan-discover.1.gz
complete -c airscan-discover -o test-fast -l test-fast -d 'Fast discovery mode (see ane-airscan(5) for details)'
complete -c airscan-discover -o test-auto -l test-auto -d 'Automatic protocol selection (see ane-airscan(5) for details)'
complete -c airscan-discover -s d -d 'Print debug messages to console'
complete -c airscan-discover -s t -d 'Write a very detailed protocol trace to airscan-discover-zeroconf'

