# annobin
# Autogenerated from man page /usr/share/man/man1/annobin.1.gz
complete -c annobin -o D_FORTIFY_SOURCE -d el
complete -c annobin -o D_GLIBCXX_ASSERTIONS -d el
complete -c annobin -o fplugin
complete -c annobin -o Xclang -o plugin-arg-annobin-disable -d 'llvm\\fR) can be used'
complete -c annobin -l notes -d 'output:         Displaying notes found in: . gnu. build'
complete -c annobin -o 'p.annobin.notes' -d 'example of the output:         String dump of section . annobin'
complete -c annobin -o 'fplugin-arg-annobin-<option>'
complete -c annobin -o 'plugin-arg-annobin-<option>' -d 'llvm\\fR) on the command line'

