# bdf2gdfont.pl
# Autogenerated from man page /usr/share/man/man1/bdf2gdfont.pl.1.gz
complete -c 'bdf2gdfont.pl' -o 'B&H-LucidaTypewriter-Bold-R-Normal-Sans-18-180-75-75-M-110-ISO8859-10' -d '3.  Using the pcf2bdf utility.  4'

