# blivet-gui
# Autogenerated from man page /usr/share/man/man1/blivet-gui.1.gz
complete -c blivet-gui -s h -l help -d 'show this help information and exit'
complete -c blivet-gui -s v -l version -d 'show version information and exit'
complete -c blivet-gui -l keep-above -d 'keep the blivet-gui window above other windows'
complete -c blivet-gui -l auto-dev-updates -d 'gather all information about devices even if it requires potentially dangerou…'

