# cpuid
# Autogenerated from man page /usr/share/man/man1/cpuid.1.gz
complete -c cpuid -s 1 -l one-cpu -d 'Display information only for the first CPU'
complete -c cpuid -s f -l file -d 'Read raw hex information from FILE instead of from executions of the cpuid  i…'
complete -c cpuid -s l -l leaf -d 'Display information only for the specified LEAF'
complete -c cpuid -s s -l subleaf -d 'Display information only for the specified SUBLEAF'
complete -c cpuid -s h -s H -l help -d 'Display help information'
complete -c cpuid -s i -l inst -d 'Use the CPUID instruction.   The information it provides is reliable'
complete -c cpuid -s k -l kernel -d 'Use the CPUID kernel module'
complete -c cpuid -s r -l raw -d 'Display only raw hex information with no decoding'
complete -c cpuid -s v -l version -d 'Display cpuid version'

