# criu
# Autogenerated from man page /usr/share/man/man8/criu.8.gz
complete -c criu -s v -l verbosity
complete -c criu -o vnum
complete -c criu -o v0 -d 'no output; oc'
complete -c criu -o v1 -d 'only errors; oc'
complete -c criu -o v2 -d 'above plus warnings (this is the default level); oc'
complete -c criu -o v3 -d 'above plus information messages and timestamps; oc'
complete -c criu -o v4 -d 'above plus lots of debug'
complete -c criu -l config
complete -c criu -l no-default-config
complete -c criu -l pidfile
complete -c criu -s o -l log-file
complete -c criu -l display-stats
complete -c criu -s D -l images-dir
complete -c criu -l stream
complete -c criu -l prev-images-dir
complete -c criu -s W -l work-dir
complete -c criu -l close
complete -c criu -s L -l libdir
complete -c criu -l enable-fs
complete -c criu -l action-script
complete -c criu -l unprivileged
complete -c criu -s V -l version
complete -c criu -s h -l help
complete -c criu -l track-mem
complete -c criu -l pre-dump-mode
complete -c criu -s t -l tree
complete -c criu -s R -l leave-running
complete -c criu -s s -l leave-stopped
complete -c criu -l external
complete -c criu -l freeze-cgroup
complete -c criu -l manage-cgroups
complete -c criu -l cgroup-props
complete -c criu -l cgroup-props-file
complete -c criu -l cgroup-dump-controller
complete -c criu -l cgroup-yard
complete -c criu -l tcp-established
complete -c criu -l tcp-close
complete -c criu -l skip-in-flight
complete -c criu -l evasive-devices
complete -c criu -l page-server
complete -c criu -l force-irmap
complete -c criu -l auto-dedup
complete -c criu -s l -l file-locks
complete -c criu -l link-remap
complete -c criu -l timeout
complete -c criu -l ghost-limit
complete -c criu -l ghost-fiemap
complete -c criu -s j -l shell-job
complete -c criu -l cpu-cap
complete -c criu -l cgroup-root
complete -c criu -l lazy-pages
complete -c criu -l file-validation
complete -c criu -l network-lock
complete -c criu -l inherit-fd
complete -c criu -s d -l restore-detached
complete -c criu -s S -l restore-sibling
complete -c criu -l log-pid
complete -c criu -s r -l root
complete -c criu -s J -l join-ns
complete -c criu -l veth-pair
complete -c criu -l lsm-profile
complete -c criu -l lsm-mount-context
complete -c criu -l weak-sysctls
complete -c criu -l skip-file-rwx-check
complete -c criu -l extra
complete -c criu -l experimental
complete -c criu -l all
complete -c criu -l feature
complete -c criu -l daemon
complete -c criu -l status-fd
complete -c criu -l address
complete -c criu -l port
complete -c criu -l ps-socket
complete -c criu -l tls-cacert
complete -c criu -l tls-cacrl
complete -c criu -l tls-cert
complete -c criu -l tls-key
complete -c criu -l tls

