# dm_date
# Autogenerated from man page /usr/share/man/man1/dm_date.1.gz
complete -c dm_date -s h -l help
complete -c dm_date -s d -l date
complete -c dm_date -s f -l file
complete -c dm_date -s r -l reference
complete -c dm_date -s R -l rfc-2822
complete -c dm_date -s u -l utc -l universal

