# dtrust-tool
# Autogenerated from man page /usr/share/man/man1/dtrust-tool.1.gz
complete -c dtrust-tool -l check-transport-protection -s c -d 'In the delivery state the card is locked by a so called transport protection'
complete -c dtrust-tool -l help -s h -d 'Print help message on screen'
complete -c dtrust-tool -l reader -s r -d 'Number of the reader to use'
complete -c dtrust-tool -l pin-status -s s -d 'Show the status of the various PINs'
complete -c dtrust-tool -l unlock-transport-protection -s u -d 'This command removes the transport protection'
complete -c dtrust-tool -l verbose -s v -d 'Causes dtrust-tool to be more verbose'
complete -c dtrust-tool -l wait -s w -d 'Causes dtrust-tool to wait for the token to be inserted into reader'

