# epstopdf
# Autogenerated from man page /usr/share/man/man1/epstopdf.1.gz
complete -c epstopdf -l help -d 'display help message and exit'
complete -c epstopdf -l version -d 'display version information and exit'
complete -c epstopdf -l outfile -d 'write result to file'
complete -c epstopdf -l debug -d 'write debugging info (default: false)'
complete -c epstopdf -l exact -d 'scan ExactBoundingBox (default: false)'
complete -c epstopdf -l filter -d 'read standard input and (unless --outfile is given) write standard output (de…'
complete -c epstopdf -l gs -d 'run Ghostscript (default: true)'
complete -c epstopdf -l hires -d 'scan HiresBoundingBox (default: false)'
complete -c epstopdf -l restricted -d 'turn on restricted mode (default: [true for repstopdf, else false]); this for…'
complete -c epstopdf -l gscmd -d 'pipe output to val (default: [gswin64c on 64-bit Windows, gswin32c on 32-bit …'
complete -c epstopdf -l gsopt -d 'include val as one argument in the gs command (can be repeated)'
complete -c epstopdf -l gsopts -d 'split val at whitespace and include each resulting word as an argument in the…'
complete -c epstopdf -l autorotate -d 'set AutoRotatePages (default: None); recognized val choices: None, All, PageB…'
complete -c epstopdf -l compress -d 'use compression in the output (default: true); if turned off, passes R -dUseF…'
complete -c epstopdf -l device -d 'use -sDEVICE=dev (default: pdfwrite); not allowed in restricted mode'
complete -c epstopdf -l embed -d 'embed fonts (default: true); passes  -dMaxSubsetPct=100 -dSubsetFonts=true -d…'
complete -c epstopdf -l gray -d 'grayscale output (default: false); passes  -sColorConversionStrategy=Gray -dP…'
complete -c epstopdf -l pdfsettings -d 'use -dPDFSETTINGS=/val (default is `prepress\' if --embed, else empty); recogn…'
complete -c epstopdf -l quiet -d 'use -q, a. k. a.  -dQUIET (default: false)'
complete -c epstopdf -l res -d 'set image resolution (default: [use gs default]); ignored if --debug is set'
complete -c epstopdf -o dCompatibilityLevel
complete -c epstopdf -l nogs -d 'otherwise, the default is to construct the output file name by replacing any …'
complete -c epstopdf -o dUseFlateCompression
complete -c epstopdf -o dMaxSubsetPct -o dSubsetFonts -o dEmbedAllFonts
complete -c epstopdf -o sColorConversionStrategy -o dProcessColorModel
complete -c epstopdf -l safer -d 'use -d(NO)QUIET (default: true)'

