# innochecksum
# Autogenerated from man page /usr/share/man/man1/innochecksum.1.gz
complete -c innochecksum -s '?' -l help
complete -c innochecksum -s a -l allow-mismatches
complete -c innochecksum -s c -l count
complete -c innochecksum -s e -l end-page
complete -c innochecksum -s i -l per-page-details
complete -c innochecksum -s I -l info
complete -c innochecksum -s f -l leaf
complete -c innochecksum -s l -l log
complete -c innochecksum -s m -l merge
complete -c innochecksum -s n -l no-check
complete -c innochecksum -s p -l page-num
complete -c innochecksum -s D -l page-type-dump
complete -c innochecksum -s S -l page-type-summary
complete -c innochecksum -s s -l start-page
complete -c innochecksum -s u -l skip-corrupt
complete -c innochecksum -s C -l strict-check
complete -c innochecksum -s w -l write
complete -c innochecksum -s v -l verbose
complete -c innochecksum -s V -l version

