# jcmd-java-17-openjdk-17.0.9.0.9-3.fc39.x86_64
# Autogenerated from man page /usr/share/man/man1/jcmd-java-17-openjdk-17.0.9.0.9-3.fc39.x86_64.1.gz
complete -c 'jcmd-java-17-openjdk-17.0.9.0.9-3.fc39.x86_64' -o all -d 'Compiler. codecache Prints code cache layout and bounds.  Impact: Low'
complete -c 'jcmd-java-17-openjdk-17.0.9.0.9-3.fc39.x86_64' -s l -d '(BOOLEAN, false) VM'
complete -c 'jcmd-java-17-openjdk-17.0.9.0.9-3.fc39.x86_64' -s i -d '(BOOLEAN, false) [bu] 2'
complete -c 'jcmd-java-17-openjdk-17.0.9.0.9-3.fc39.x86_64' -s s -d subclasses
complete -c 'jcmd-java-17-openjdk-17.0.9.0.9-3.fc39.x86_64' -o verbose -d 'table (BOOLEAN, false) VM. symboltable [options] Dumps the symbol table'
complete -c 'jcmd-java-17-openjdk-17.0.9.0.9-3.fc39.x86_64' -o date -d '(BOOLEAN, false) VM. version Prints JVM version information.  Impact: Low'

