# kpat
# Autogenerated from man page /usr/share/man/man6/kpat.6.gz
complete -c kpat -s h -l help -d 'This lists the options available at the command line'
complete -c kpat -s v -l version -d 'Lists version information for KPatience'
complete -c kpat -l solvegame -d 'Try to find a solution to the given savegame'
complete -c kpat -l solve -d 'Dealer to solve (debug)'
complete -c kpat -l start -d 'Game range start (default 0:INT_MAX)'
complete -c kpat -l end -d 'Game range end (default start:start if start given)'
complete -c kpat -l gametype -d 'Skip the selection screen and load a particular game type'
complete -c kpat -l testdir -d 'Directory with test cases'
complete -c kpat -l generate -d 'Generate random test cases'
complete -c kpat -l author -d 'Lists KPatience\\*(Aqs authors in the terminal window'
complete -c kpat -l license -d 'Shows license information'
complete -c kpat -l desktopfile -d 'The base file name of the desktop entry for this application'

