# krusader
# Autogenerated from man page /usr/share/man/man1/krusader.1.gz
complete -c krusader -s h -l help -d 'this lists the options available at the command line'
complete -c krusader -s v -l version -d 'lists version information for Krusader'
complete -c krusader -l author -d 'show the authors'
complete -c krusader -l license -d 'show the license'
complete -c krusader -l left -d 'start left panel at <path>'
complete -c krusader -l right -d 'start right panel at <path>'
complete -c krusader -l profile -d 'load <panel-profile> on startup'
complete -c krusader -s d -l debug -d 'enables debug output'

