# llvm-remark-size-diff
# Autogenerated from man page /usr/share/man/man1/llvm-remark-size-diff.1.gz
complete -c llvm-remark-size-diff -l parser -d 'Select the type of input remark parser.  Required'
complete -c llvm-remark-size-diff -l report-style -d 'Output style.  * human: Human-readable textual report.  Default option'
complete -c llvm-remark-size-diff -l pretty -d 'Pretty-print JSON output.  Optional'
complete -c llvm-remark-size-diff -s o -d 'Output file for the report.  Outputs to stdout by default'

