# nvme-ocp-clear-pcie-correctable-error-counters
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-clear-pcie-correctable-error-counters.1.gz
complete -c nvme-ocp-clear-pcie-correctable-error-counters -s n -l no-uuid -d 'Do not try to automatically detect UUID index for this command (required for …'

