# nvme-write-uncor
# Autogenerated from man page /usr/share/man/man1/nvme-write-uncor.1.gz
complete -c nvme-write-uncor -l start-block -s s -d 'Start block'
complete -c nvme-write-uncor -l block-count -s c -d 'Number of logical blocks to write uncorrectable'
complete -c nvme-write-uncor -l namespace-id -s n -d 'Namespace ID use in the command'
complete -c nvme-write-uncor -s T -l dir-type -d 'Directive type'
complete -c nvme-write-uncor -s S -l dir-spec -d 'Directive specific'

