# nvme-nvme-mi-send
# Autogenerated from man page /usr/share/man/man1/nvme-nvme-mi-send.1.gz
complete -c nvme-nvme-mi-send -s o -l opcode -d 'The NVMe-MI opcode to send to the device in the command'
complete -c nvme-nvme-mi-send -s n -l namespace-id -d 'The value for the ns-id in the command'
complete -c nvme-nvme-mi-send -s l -l data-len -d 'The data length for the buffer used for this command'
complete -c nvme-nvme-mi-send -s m -l nmimt -d 'The value for the NVMe-MI message type in the command'
complete -c nvme-nvme-mi-send -s 0 -l nmd0 -d 'The value for the NVMe management request dword 0 in the command'
complete -c nvme-nvme-mi-send -s 1 -l nmd1 -d 'The value for the NVMe management request dword 1 in the command'
complete -c nvme-nvme-mi-send -s i -l input-file -d 'If the command is a data-out (write) command, use this file to fill the buffe…'

