# nvme-ocp-eol-plp-failure-mode
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-eol-plp-failure-mode.1.gz
complete -c nvme-ocp-eol-plp-failure-mode -s m -l mode -d 'Set the EOL or PLP circuitry failure mode to [0-3] (0: default, 1: rom, 2: wt…'
complete -c nvme-ocp-eol-plp-failure-mode -s n -l no-uuid -d 'Do not try to automatically detect UUID index for this command (required for …'
complete -c nvme-ocp-eol-plp-failure-mode -s s -l save -d 'Save the attribute so that it persists through all power states and resets'
complete -c nvme-ocp-eol-plp-failure-mode -l sel -d 'Select (SEL): This field specifies which value of the attributes to return in…'

