# opusdec
# Autogenerated from man page /usr/share/man/man1/opusdec.1.gz
complete -c opusdec -s h -l help -d 'Show help message'
complete -c opusdec -s V -l version -d 'Show version information'
complete -c opusdec -l quiet -d 'Suppresses program output'
complete -c opusdec -l rate -d 'br Force decoding at sampling rate n Hz'
complete -c opusdec -l force-stereo -d 'br Force decoding to stereo'
complete -c opusdec -l gain -d 'br Adjust the output volume n dB, negative values make the signal quieter'
complete -c opusdec -l no-dither -d 'Do not dither 16-bit output'
complete -c opusdec -l float -d 'Output 32-bit floating-point samples instead of 16-bit integer samples'
complete -c opusdec -l force-wav -d 'Force including a Wave header on output (e. g'
complete -c opusdec -l packet-loss -d 'Simulate n % random Opus packet loss'

