# opusinfo
# Autogenerated from man page /usr/share/man/man1/opusinfo.1.gz
complete -c opusinfo -s h -d 'Show a help and usage message'
complete -c opusinfo -s q -d 'Quiet mode.  This may be specified multiple times'
complete -c opusinfo -s v -d 'Verbose mode.  At the current time, this does not do anything'
complete -c opusinfo -s V -d 'Show program version info and exit'

