# pandoc-lua
# Autogenerated from man page /home/rad1an/.local/share/man/man1/pandoc-lua.1.gz
complete -c pandoc-lua -s e -d 'Execute statement stat'
complete -c pandoc-lua -s l -d 'If mod has the pattern g=m, then require library m into global g; otherwise r…'
complete -c pandoc-lua -s v -d 'Show version information'
complete -c pandoc-lua -s i -d 'Enter interactive mode after running script'
complete -c pandoc-lua -s E -d 'Ignore environment variables'
complete -c pandoc-lua -s W -d 'Turn warnings on.  INTERACTIVE MODE'

