# pandoc-server
# Autogenerated from man page /home/rad1an/.local/share/man/man1/pandoc-server.1.gz
complete -c pandoc-server -l port -d 'HTTP port on which to run the server.  Default: 3030'
complete -c pandoc-server -l timeout -d 'Timeout in seconds, after which a conversion is killed.  Default: 2'
complete -c pandoc-server -l help -d 'Print this help'
complete -c pandoc-server -l version -d 'Print version.  API Root endpoint'

