# perf-list
# Autogenerated from man page /usr/share/man/man1/perf-list.1.gz
complete -c perf-list -s d -l desc -d 'Print extra event descriptions.  (default)'
complete -c perf-list -l no-desc -d 'Don\'t print descriptions'
complete -c perf-list -s v -l long-desc -d 'Print longer event descriptions'
complete -c perf-list -l debug -d 'Enable debugging output'
complete -c perf-list -l details -d 'Print how named events are resolved internally into perf events, and also any…'
complete -c perf-list -l deprecated -d 'Print deprecated events.  By default the deprecated events are hidden'
complete -c perf-list -l unit -d 'Print PMU events and metrics limited to the specific PMU name.  (e. g'
complete -c perf-list -s j -l json -d 'Output in JSON format'
complete -c perf-list -s o -l output -d 'Output file name.  By default output is written to stdout'
complete -c perf-list -l raw-dump -d ' 2. c   2.  4. 2'

