# perf-timechart
# Autogenerated from man page /usr/share/man/man1/perf-timechart.1.gz
complete -c perf-timechart -s o -l output
complete -c perf-timechart -s i -l input
complete -c perf-timechart -s w -l width
complete -c perf-timechart -s P -l power-only
complete -c perf-timechart -s T -l tasks-only
complete -c perf-timechart -s p -l process
complete -c perf-timechart -s f -l force
complete -c perf-timechart -l symfs
complete -c perf-timechart -s n -l proc-num
complete -c perf-timechart -s t -l topology
complete -c perf-timechart -l highlight
complete -c perf-timechart -l io-skip-eagain
complete -c perf-timechart -l io-min-time
complete -c perf-timechart -l io-merge-dist
complete -c perf-timechart -s I -l io-only
complete -c perf-timechart -s g -l callchain

