# perf-data
# Autogenerated from man page /usr/share/man/man1/perf-data.1.gz
complete -c perf-data -l to-ctf
complete -c perf-data -l to-json
complete -c perf-data -l tod
complete -c perf-data -s i
complete -c perf-data -s f -l force
complete -c perf-data -s v -l verbose
complete -c perf-data -l all

