# perf-kwork
# Autogenerated from man page /usr/share/man/man1/perf-kwork.1.gz
complete -c perf-kwork -s D -l dump-raw-trace -d 'Display verbose dump of the sched data'
complete -c perf-kwork -s f -l force -d 'Don\'t complain, do it'
complete -c perf-kwork -s k -l kwork -d 'List of kwork to profile (irq, softirq, workqueue, sched, etc)'
complete -c perf-kwork -s v -l verbose -d 'Be more verbose.  (show symbol address, etc)'
complete -c perf-kwork -s b -l use-bpf -d 'Use BPF to measure kwork latency'
complete -c perf-kwork -s C -l cpu -d 'Only show events for the given CPU(s) (comma separated list)'
complete -c perf-kwork -s i -l input -d 'Input file name.  (default: perf. data unless stdin is a fifo)'
complete -c perf-kwork -s n -l name -d 'Only show events for the given name'
complete -c perf-kwork -s s -l sort -d 'Sort by key(s): avg, max, count'
complete -c perf-kwork -l time -d 'Only analyze samples within given time window: <start>,<stop>'
complete -c perf-kwork -l --------------- -l --------------- -l ---- -l ----------------------- -l -------- -l -------- -d '   1811186. 976062     1811186'
complete -c perf-kwork -s S
complete -c perf-kwork -l with-summary -d '        Show summary with statistics'
complete -c perf-kwork -s g -l call-graph
complete -c perf-kwork -l vmlinux
complete -c perf-kwork -l kallsyms
complete -c perf-kwork -l max-stack
complete -c perf-kwork -l symfs

