# perf-test
# Autogenerated from man page /usr/share/man/man1/perf-test.1.gz
complete -c perf-test -s s -l skip -d 'Tests to skip (comma separated numeric list)'
complete -c perf-test -s v -l verbose -d 'Be more verbose'
complete -c perf-test -s F -l dont-fork -d 'Do not fork child for each test, run all tests within single process'
complete -c perf-test -l dso -d 'Specify a DSO for the "Symbols" test'

