# perf-buildid-cache
# Autogenerated from man page /usr/share/man/man1/perf-buildid-cache.1.gz
complete -c perf-buildid-cache -s a -l add -d 'Add specified file to the cache'
complete -c perf-buildid-cache -s f -l force -d 'Don\'t complain, do it'
complete -c perf-buildid-cache -s k -l kcore -d 'Add specified kcore file to the cache'
complete -c perf-buildid-cache -s r -l remove -d 'Remove a cached binary which has same build-id of specified file from the cac…'
complete -c perf-buildid-cache -s p -l purge -d 'Purge all cached binaries including older caches which have specified path fr…'
complete -c perf-buildid-cache -s P -l purge-all -d 'Purge all cached binaries.  This will flush out entire cache'
complete -c perf-buildid-cache -s M -l missing -d 'List missing build ids in the cache for the specified file'
complete -c perf-buildid-cache -s u -l update -d 'Update specified file of the cache'
complete -c perf-buildid-cache -s l -l list -d 'List all valid binaries from cache'
complete -c perf-buildid-cache -s v -l verbose -d 'Be more verbose'
complete -c perf-buildid-cache -l debuginfod -d 'Specify debuginfod URL to be used when retrieving perf'
complete -c perf-buildid-cache -l target-ns

