# perf-evlist
# Autogenerated from man page /usr/share/man/man1/perf-evlist.1.gz
complete -c perf-evlist -s i -l input -d 'Input file name.  (default: perf. data unless stdin is a fifo)'
complete -c perf-evlist -s f -l force -d 'Don\'t complain, do it'
complete -c perf-evlist -s F -l freq -d 'Show just the sample frequency used for each event'
complete -c perf-evlist -s v -l verbose -d 'Show all fields'
complete -c perf-evlist -s g -l group -d 'Show event group information'
complete -c perf-evlist -l trace-fields -d 'Show tracepoint field names'

