# perf-mem
# Autogenerated from man page /usr/share/man/man1/perf-mem.1.gz
complete -c perf-mem -s i -l input -d 'Input file name'
complete -c perf-mem -s f -l force -d 'Don\'t do ownership validation'
complete -c perf-mem -s t -l type -d 'Select the memory operation type: load or store (default: load,store)'
complete -c perf-mem -s D -l dump-raw-samples -d 'Dump the raw decoded samples on the screen in a format that is easy to parse …'
complete -c perf-mem -s x -l field-separator -d 'Specify the field separator used when dump raw samples (-D option)'
complete -c perf-mem -s C -l cpu -d 'Monitor only on the list of CPUs provided'
complete -c perf-mem -s U -l hide-unresolved -d 'Only display entries resolved to a symbol'
complete -c perf-mem -s p -l phys-data -d 'Record/Report sample physical addresses'
complete -c perf-mem -l data-page-size -d 'Record/Report sample data address page size'
complete -c perf-mem -s e -l event
complete -c perf-mem -s K -l all-kernel
complete -c perf-mem -l all-user
complete -c perf-mem -s v -l verbose
complete -c perf-mem -l ldlat

