# perf-kallsyms
# Autogenerated from man page /usr/share/man/man1/perf-kallsyms.1.gz
complete -c perf-kallsyms -s v -l verbose -d 'Increase verbosity level, showing details about symbol table loading, etc'

