# perf-kvm
# Autogenerated from man page /usr/share/man/man1/perf-kvm.1.gz
complete -c perf-kvm -s i -l input -d 'Input file name, for the report, diff and buildid-list subcommands'
complete -c perf-kvm -s o -l output -d 'Output file name, for the record subcommand'
complete -c perf-kvm -l host -d 'Collect host side performance profile'
complete -c perf-kvm -l guest -d 'Collect guest side performance profile'
complete -c perf-kvm -l guestmount -d 'Guest OS root file system mount directory'
complete -c perf-kvm -l guestkallsyms -d 'Guest OS /proc/kallsyms file copy.  perf reads it to get guest kernel symbols'
complete -c perf-kvm -l guestmodules -d 'Guest OS /proc/modules file copy'
complete -c perf-kvm -l guestvmlinux -d 'Guest OS kernel vmlinux'
complete -c perf-kvm -l guest-code -d 'Indicate that guest code can be found in the hypervisor process, which is a c…'
complete -c perf-kvm -l stdio -d 'Use the stdio interface'
complete -c perf-kvm -s v -l verbose -d 'Be more verbose (show counter open errors, etc)'
complete -c perf-kvm -l vcpu
complete -c perf-kvm -l event
complete -c perf-kvm -s k -l key
complete -c perf-kvm -s p -l pid
complete -c perf-kvm -s d -l display
complete -c perf-kvm -s m -l mmap-pages
complete -c perf-kvm -s a -l all-cpus
complete -c perf-kvm -l duration
complete -c perf-kvm -l proc-map-timeout

