# perf-intel-pt
# Autogenerated from man page /usr/share/man/man1/perf-intel-pt.1.gz
complete -c perf-intel-pt -l insn-trace -d 'oc o 2. 3'
complete -c perf-intel-pt -l src-trace -d 'The intel-pt-events. py script also has options: oc o 2. 3'
complete -c perf-intel-pt -l all-switch-events -d 'oc o 2. 3'
complete -c perf-intel-pt -l interleave -d 'n defaults to 4'
complete -c perf-intel-pt -s e -d 'will use a default config value.  Currently that is the same as'
complete -c perf-intel-pt -l ---------------------------------------------------------- -d 'perf_event_attr: type                             6 size                     …'
complete -c perf-intel-pt -l aux-sample -d 'Optionally it can be followed by the sample size in bytes e. g'
complete -c perf-intel-pt -s S -d 'Optionally it can be followed by the snapshot size e. g'
complete -c perf-intel-pt -o S0x100000 -d 'The default snapshot size is the auxtrace mmap size'
complete -c perf-intel-pt -s m -d 'selects a buffer size of 16 pages i. e.  64KiB'
complete -c perf-intel-pt -l itrace -d 'which, in turn, is the same as'
complete -c perf-intel-pt -s o
complete -c perf-intel-pt -s l -d 'For example, for errors but not overflow or data lost errors:'
complete -c perf-intel-pt -s a -d '+a      Log all perf events +e      Output only on decoding errors (size conf…'

