# perf-sched
# Autogenerated from man page /usr/share/man/man1/perf-sched.1.gz
complete -c perf-sched -s i -l input -d 'Input file name.  (default: perf. data unless stdin is a fifo)'
complete -c perf-sched -s v -l verbose -d 'Be more verbose.  (show symbol address, etc)'
complete -c perf-sched -s D -l dump-raw-trace -d 'Display verbose dump of the sched data'
complete -c perf-sched -s f -l force -d 'Don\'t complain, do it'
complete -c perf-sched -l compact
complete -c perf-sched -l cpus
complete -c perf-sched -l color-cpus
complete -c perf-sched -l color-pids
complete -c perf-sched -s k -l vmlinux
complete -c perf-sched -l kallsyms
complete -c perf-sched -s g -l call-graph
complete -c perf-sched -l max-stack
complete -c perf-sched -s C -l cpu
complete -c perf-sched -s p -l pid
complete -c perf-sched -s t -l tid
complete -c perf-sched -s s -l summary
complete -c perf-sched -s S -l with-summary
complete -c perf-sched -l symfs
complete -c perf-sched -s V -l cpu-visual
complete -c perf-sched -s w -l wakeups
complete -c perf-sched -s M -l migrations
complete -c perf-sched -s n -l next
complete -c perf-sched -s I -l idle-hist
complete -c perf-sched -l time
complete -c perf-sched -l state

