# perf-script-python
# Autogenerated from man page /usr/share/man/man1/perf-script-python.1.gz
complete -c perf-script-python -l -------------------------------------- -l --------- -d 'sys_write                                     455067 sys_getdents            …'
complete -c perf-script-python -o rw-r--r-- -d 'drwxr-xr-x 3 trz trz 4096 2010-01-26 22:49 Perf-Trace-Util'

