# perf-config
# Autogenerated from man page /usr/share/man/man1/perf-config.1.gz
complete -c perf-config -s l -l list -d 'Show current config variables, name and value, for all sections'
complete -c perf-config -l user -d 'For writing and reading options: write to user $HOME/'
complete -c perf-config -l system -d 'For writing and reading options: write to system-wide $(sysconfdir)/perfconfi…'
complete -c perf-config -s M -d 'option help in the objdump man page.  annotate. hide_src_code'
complete -c perf-config -l slab -d nor
complete -c perf-config -l page -d 'option is used.  Default is slab.  record. *, record. build-id'

