# perf-script
# Autogenerated from man page /usr/share/man/man1/perf-script.1.gz
complete -c perf-script -s D -l dump-raw-trace -d 'Display verbose dump of the trace data'
complete -c perf-script -l dump-unsorted-raw-trace -d 'Same as --dump-raw-trace but not sorted in time order'
complete -c perf-script -s L -l Latency -d 'Show latency attributes (irqs/preemption disabled, etc)'
complete -c perf-script -s l -l list -d 'Display a list of available trace scripts'
complete -c perf-script -s s -l script -d 'Process trace data with the given script ([lang]:script[. ext])'
complete -c perf-script -s g -l gen-script -d 'Generate perf-script'
complete -c perf-script -l dlfilter -d 'Filter sample events using the given shared object file'
complete -c perf-script -l dlarg -d 'Pass arg as an argument to the dlfilter'
complete -c perf-script -l list-dlfilters -d 'Display a list of available dlfilters'
complete -c perf-script -s a -d 'Force system-wide collection'
complete -c perf-script -s i -l input -d 'Input file name.  (default: perf. data unless stdin is a fifo)'
complete -c perf-script -s d -l debug-mode -d 'Do various checks like samples ordering and lost events'
complete -c perf-script -s F -l fields -d 'Comma separated list of fields to print'
complete -c perf-script -s k -l vmlinux -d 'vmlinux pathname'
complete -c perf-script -l kallsyms -d 'kallsyms pathname'
complete -c perf-script -l symfs -d 'Look for files with symbols relative to this directory'
complete -c perf-script -s G -l hide-call-graph -d 'When printing symbols do not display call chain'
complete -c perf-script -l stop-bt -d 'Stop display of callgraph at these symbols'
complete -c perf-script -s C -l cpu -d 'Only report samples for the list of CPUs provided'
complete -c perf-script -s c -l comms -d 'Only display events for these comms'
complete -c perf-script -l pid -d 'Only show events for given process ID (comma separated list)'
complete -c perf-script -l tid -d 'Only show events for given thread ID (comma separated list)'
complete -c perf-script -s I -l show-info -d 'Display extended information about the perf. data file'
complete -c perf-script -l show-kernel-path -d 'Try to resolve the path of [kernel. kallsyms]'
complete -c perf-script -l demangle -d 'Demangle symbol names to human readable form'
complete -c perf-script -l demangle-kernel -d 'Demangle kernel symbol names to human readable form (for C++ kernels)'
complete -c perf-script -l itrace -d 'Options for decoding instruction tracing data.  The options are: . sp '
complete -c perf-script -l full-source-path -d 'Show the full path for source files for srcline output'
complete -c perf-script -l max-stack -d 'Set the stack depth limit when parsing the callchain, anything beyond the spe…'
complete -c perf-script -l ns -d 'Use 9 decimal places when displaying time (i. e.  show the nanoseconds)'
complete -c perf-script -s f -l force -d 'Don\'t do ownership validation'
complete -c perf-script -l time -d 'Only analyze samples within given time window: <start>,<stop>'
complete -c perf-script -l max-blocks -d 'Set the maximum number of program blocks to print with brstackinsn for each s…'
complete -c perf-script -l reltime -d 'Print time stamps relative to trace start'
complete -c perf-script -l deltatime -d 'Print time stamps relative to previous event'
complete -c perf-script -l per-event-dump -d 'Create per event files with a "perf. data. EVENT'
complete -c perf-script -l inline -d 'If a callgraph address belongs to an inlined function, the inline stack will …'
complete -c perf-script -l insn-trace -d 'Show instruction stream for intel_pt traces'
complete -c perf-script -l xed -d 'Run xed disassembler on output.  Requires installing the xed disassembler'
complete -c perf-script -s S -l symbols -d 'Only consider the listed symbols'
complete -c perf-script -l addr-range -d 'Use with -S or --symbols to list traced records within address range. sp '
complete -c perf-script -l dsos -d 'Only consider symbols in these DSOs'
complete -c perf-script -l call-trace -d 'Show call stream for intel_pt traces'
complete -c perf-script -l call-ret-trace -d 'Show call and return stream for intel_pt traces'
complete -c perf-script -l graph-function -d 'For itrace only show specified functions and their callees for itrace'
complete -c perf-script -l switch-on -d 'Only consider events after this event is found'
complete -c perf-script -l switch-off -d 'Stop considering events after this event is found'
complete -c perf-script -l show-on-off-events -d 'Show the --switch-on/off events too'
complete -c perf-script -l stitch-lbr -d 'Show callgraph with stitched LBRs, which may have more complete callgraph'
complete -c perf-script -l guestmount -d 'Guest OS root file system mount directory'
complete -c perf-script -l guestkallsyms -d 'Guest OS /proc/kallsyms file copy.  perf reads it to get guest kernel symbols'
complete -c perf-script -l guestmodules -d 'Guest OS /proc/modules file copy'
complete -c perf-script -l guestvmlinux -d 'Guest OS kernel vmlinux'
complete -c perf-script -l guest-code -d 'Indicate that guest code can be found in the hypervisor process, which is a c…'
complete -c perf-script -o cpu -d 'removes the cpu field and adds the insn field'
complete -c perf-script -o Fsw:-cpu -o period -d 'removes cpu and period from software events'
complete -c perf-script -l show-task-events
complete -c perf-script -l show-mmap-events
complete -c perf-script -l show-namespace-events
complete -c perf-script -l show-switch-events
complete -c perf-script -l show-lost-events
complete -c perf-script -l show-round-events
complete -c perf-script -l show-bpf-events
complete -c perf-script -l show-cgroup-events
complete -c perf-script -l show-text-poke-events
complete -c perf-script -l header
complete -c perf-script -l header-only

