# perf-ftrace
# Autogenerated from man page /usr/share/man/man1/perf-ftrace.1.gz
complete -c perf-ftrace -s p -l pid
complete -c perf-ftrace -l tid
complete -c perf-ftrace -s a -l all-cpus
complete -c perf-ftrace -s C -l cpu
complete -c perf-ftrace -s v -l verbose
complete -c perf-ftrace -s t -l tracer
complete -c perf-ftrace -s F -l funcs
complete -c perf-ftrace -s D -l delay
complete -c perf-ftrace -s m -l buffer-size
complete -c perf-ftrace -l inherit
complete -c perf-ftrace -s T -l trace-funcs
complete -c perf-ftrace -s N -l notrace-funcs
complete -c perf-ftrace -l func-opts
complete -c perf-ftrace -s G -l graph-funcs
complete -c perf-ftrace -s g -l nograph-funcs
complete -c perf-ftrace -l graph-opts
complete -c perf-ftrace -s b -l use-bpf
complete -c perf-ftrace -s n -l use-nsec

