# perf-lock
# Autogenerated from man page /usr/share/man/man1/perf-lock.1.gz
complete -c perf-lock -s i -l input
complete -c perf-lock -l output
complete -c perf-lock -s v -l verbose
complete -c perf-lock -s q -l quiet
complete -c perf-lock -s D -l dump-raw-trace
complete -c perf-lock -s f -l force
complete -c perf-lock -l vmlinux
complete -c perf-lock -l kallsyms
complete -c perf-lock -s k -l key
complete -c perf-lock -s F -l field
complete -c perf-lock -s c -l combine-locks
complete -c perf-lock -s t -l threads
complete -c perf-lock -s E -l entries
complete -c perf-lock -s m -l map
complete -c perf-lock -s b -l use-bpf
complete -c perf-lock -s a -l all-cpus
complete -c perf-lock -s C -l cpu
complete -c perf-lock -s p -l pid
complete -c perf-lock -l tid
complete -c perf-lock -s M -l map-nr-entries
complete -c perf-lock -l max-stack
complete -c perf-lock -l stack-skip
complete -c perf-lock -s l -l lock-addr
complete -c perf-lock -s o -l lock-owner
complete -c perf-lock -s Y -l type-filter
complete -c perf-lock -s L -l lock-filter
complete -c perf-lock -s S -l callstack-filter
complete -c perf-lock -s x -l field-separator
complete -c perf-lock -l lock-cgroup
complete -c perf-lock -s G -l cgroup-filter

