# perf
# Autogenerated from man page /usr/share/man/man1/perf.1.gz
complete -c perf -s h -l help -d 'Run perf help command'
complete -c perf -s v -l version -d 'Display perf version'
complete -c perf -o vv -d 'Print the compiled-in status of libraries'
complete -c perf -l exec-path -d 'Display or set exec path'
complete -c perf -l html-path -d 'Display html documentation path'
complete -c perf -s p -l paginate -d 'Set up pager'
complete -c perf -l no-pager -d 'Do not set pager'
complete -c perf -l buildid-dir -d 'Setup buildid cache directory.  It has higher priority than buildid'
complete -c perf -l list-cmds -d 'List the most commonly used perf commands'
complete -c perf -l list-opts -d 'List available perf options'
complete -c perf -l debugfs-dir -d 'Set debugfs directory or set environment variable PERF_DEBUGFS_DIR'
complete -c perf -l debug -d 'Setup debug variable (see list below) in value range (0, 10)'
complete -c perf -l debug-file -d 'Write debug output to a specified file'

