# perf-buildid-list
# Autogenerated from man page /usr/share/man/man1/perf-buildid-list.1.gz
complete -c perf-buildid-list -s H -l with-hits -d 'Show only DSOs with hits'
complete -c perf-buildid-list -s i -l input -d 'Input file name.  (default: perf. data unless stdin is a fifo)'
complete -c perf-buildid-list -s f -l force -d 'Don\'t do ownership validation'
complete -c perf-buildid-list -s k -l kernel -d 'Show running kernel build id'
complete -c perf-buildid-list -s m -l kernel-maps -d 'Show buildid, start/end text address, and path of running kernel and its modu…'
complete -c perf-buildid-list -s v -l verbose -d 'Be more verbose'

