# perf-c2c
# Autogenerated from man page /usr/share/man/man1/perf-c2c.1.gz
complete -c perf-c2c -s e -l event
complete -c perf-c2c -s v -l verbose
complete -c perf-c2c -s l -l ldlat
complete -c perf-c2c -s k -l all-kernel
complete -c perf-c2c -s u -l all-user
complete -c perf-c2c -l vmlinux
complete -c perf-c2c -s i -l input
complete -c perf-c2c -s N -l node-info
complete -c perf-c2c -s c -l coalesce
complete -c perf-c2c -s g -l call-graph
complete -c perf-c2c -l stdio
complete -c perf-c2c -l stats
complete -c perf-c2c -l full-symbols
complete -c perf-c2c -l no-source
complete -c perf-c2c -l show-all
complete -c perf-c2c -s f -l force
complete -c perf-c2c -s d -l display
complete -c perf-c2c -l stitch-lbr
complete -c perf-c2c -l double-cl
complete -c perf-c2c -s W -l phys-data -l sample-cpu -d 'Unless specified otherwise with -e option, following events are monitored by …'

