# perf-kmem
# Autogenerated from man page /usr/share/man/man1/perf-kmem.1.gz
complete -c perf-kmem -s i -l input -d 'For stat, select the input file (default: perf. data unless stdin is a fifo)'
complete -c perf-kmem -s f -l force -d 'Don\'t do ownership validation'
complete -c perf-kmem -s v -l verbose -d 'Be more verbose.  (show symbol address, etc)'
complete -c perf-kmem -l caller -d 'Show per-callsite statistics'
complete -c perf-kmem -l alloc -d 'Show per-allocation statistics'
complete -c perf-kmem -s s -l sort -d 'Sort the output (default: frag,hit,bytes for slab and bytes,hit for page)'
complete -c perf-kmem -s l -l line -d 'Print n lines only'
complete -c perf-kmem -l raw-ip -d 'Print raw ip instead of symbol'
complete -c perf-kmem -l slab -d 'Analyze SLAB allocator events'
complete -c perf-kmem -l page -d 'Analyze page allocator events'
complete -c perf-kmem -l live -d 'Show live page stat'
complete -c perf-kmem -l time -d 'Only analyze samples within given time window: <start>,<stop>'

