# perf-daemon
# Autogenerated from man page /usr/share/man/man1/perf-daemon.1.gz
complete -c perf-daemon -s v -l verbose -d 'Be more verbose'
complete -c perf-daemon -l config -d 'Config file path'
complete -c perf-daemon -l base -d 'Base directory path'
complete -c perf-daemon -s f -l foreground
complete -c perf-daemon -l session

