# podman-network-connect
# Autogenerated from man page /usr/share/man/man1/podman-network-connect.1.gz
complete -c podman-network-connect -l alias
complete -c podman-network-connect -l ip
complete -c podman-network-connect -l ip6
complete -c podman-network-connect -l mac-address

