# podman-manifest-push
# Autogenerated from man page /usr/share/man/man1/podman-manifest-push.1.gz
complete -c podman-manifest-push -l add-compression
complete -c podman-manifest-push -l all
complete -c podman-manifest-push -l authfile
complete -c podman-manifest-push -l cert-dir
complete -c podman-manifest-push -l compression-format
complete -c podman-manifest-push -l compression-level
complete -c podman-manifest-push -l creds
complete -c podman-manifest-push -l digestfile
complete -c podman-manifest-push -l force-compression
complete -c podman-manifest-push -l format -s f
complete -c podman-manifest-push -l quiet -s q
complete -c podman-manifest-push -l remove-signatures
complete -c podman-manifest-push -l rm
complete -c podman-manifest-push -l sign-by
complete -c podman-manifest-push -l sign-by-sigstore
complete -c podman-manifest-push -l sign-by-sigstore-private-key
complete -c podman-manifest-push -l sign-passphrase-file
complete -c podman-manifest-push -l tls-verify

