# podman-restart
# Autogenerated from man page /usr/share/man/man1/podman-restart.1.gz
complete -c podman-restart -l all -s a
complete -c podman-restart -l cidfile
complete -c podman-restart -l filter -s f
complete -c podman-restart -l latest -s l
complete -c podman-restart -l running
complete -c podman-restart -l time -s t

