# podman-secret-rm
# Autogenerated from man page /usr/share/man/man1/podman-secret-rm.1.gz
complete -c podman-secret-rm -l all -s a
complete -c podman-secret-rm -l help
complete -c podman-secret-rm -l ignore -s i

