# podman-start
# Autogenerated from man page /usr/share/man/man1/podman-start.1.gz
complete -c podman-start -l all
complete -c podman-start -l attach -s a
complete -c podman-start -l detach-keys
complete -c podman-start -l filter -s f
complete -c podman-start -l interactive -s i
complete -c podman-start -l latest -s l
complete -c podman-start -l sig-proxy

