# podman-volume-create
# Autogenerated from man page /usr/share/man/man1/podman-volume-create.1.gz
complete -c podman-volume-create -l driver -s d
complete -c podman-volume-create -l help
complete -c podman-volume-create -l ignore
complete -c podman-volume-create -l label -s l
complete -c podman-volume-create -l opt -s o

