# podman-rm
# Autogenerated from man page /usr/share/man/man1/podman-rm.1.gz
complete -c podman-rm -l all -s a
complete -c podman-rm -l cidfile
complete -c podman-rm -l depend
complete -c podman-rm -l filter
complete -c podman-rm -l force -s f
complete -c podman-rm -l ignore -s i
complete -c podman-rm -l latest -s l
complete -c podman-rm -l time -s t
complete -c podman-rm -l volumes -s v

