# podman-stop
# Autogenerated from man page /usr/share/man/man1/podman-stop.1.gz
complete -c podman-stop -l all -s a
complete -c podman-stop -l cidfile
complete -c podman-stop -l filter -s f
complete -c podman-stop -l ignore -s i
complete -c podman-stop -l latest -s l
complete -c podman-stop -l time -s t

