# podman-create
# Autogenerated from man page /usr/share/man/man1/podman-create.1.gz
complete -c podman-create -l add-host
complete -c podman-create -l annotation
complete -c podman-create -l arch
complete -c podman-create -l attach -s a
complete -c podman-create -l authfile
complete -c podman-create -l blkio-weight
complete -c podman-create -l blkio-weight-device
complete -c podman-create -l cap-add
complete -c podman-create -l cap-drop
complete -c podman-create -l cgroup-conf
complete -c podman-create -l cgroup-parent
complete -c podman-create -l cgroupns
complete -c podman-create -l cgroups
complete -c podman-create -l chrootdirs
complete -c podman-create -l cidfile
complete -c podman-create -l conmon-pidfile
complete -c podman-create -l cpu-period
complete -c podman-create -l cpu-quota
complete -c podman-create -l cpu-rt-period
complete -c podman-create -l cpu-rt-runtime
complete -c podman-create -l cpu-shares -s c
complete -c podman-create -l cpus
complete -c podman-create -l cpuset-cpus
complete -c podman-create -l cpuset-mems
complete -c podman-create -l decryption-key
complete -c podman-create -l device
complete -c podman-create -l device-cgroup-rule
complete -c podman-create -l device-read-bps
complete -c podman-create -l device-read-iops
complete -c podman-create -l device-write-bps
complete -c podman-create -l device-write-iops
complete -c podman-create -l disable-content-trust
complete -c podman-create -l dns
complete -c podman-create -l dns-option
complete -c podman-create -l dns-search
complete -c podman-create -l entrypoint
complete -c podman-create -l env -s e
complete -c podman-create -l env-file
complete -c podman-create -l env-host
complete -c podman-create -l env-merge
complete -c podman-create -l expose
complete -c podman-create -l gidmap
complete -c podman-create -l uidmap -l uidmap -d 'Note: the --gidmap option cannot be called in conjunction with the --pod opti…'
complete -c podman-create -l group-add
complete -c podman-create -l group-entry
complete -c podman-create -l health-cmd
complete -c podman-create -l health-interval
complete -c podman-create -l health-on-failure
complete -c podman-create -l health-retries
complete -c podman-create -l health-start-period
complete -c podman-create -l health-startup-cmd
complete -c podman-create -l health-startup-interval
complete -c podman-create -l health-startup-retries
complete -c podman-create -l health-startup-success
complete -c podman-create -l health-startup-timeout
complete -c podman-create -l health-timeout
complete -c podman-create -l help
complete -c podman-create -l hostname -s h
complete -c podman-create -l hostuser
complete -c podman-create -l http-proxy
complete -c podman-create -l image-volume
complete -c podman-create -l init
complete -c podman-create -l init-ctr
complete -c podman-create -l init-path
complete -c podman-create -l interactive -s i
complete -c podman-create -l ip
complete -c podman-create -l ip6
complete -c podman-create -l ipc
complete -c podman-create -l label -s l
complete -c podman-create -l label-file
complete -c podman-create -l link-local-ip
complete -c podman-create -l log-driver
complete -c podman-create -l log-opt
complete -c podman-create -l mac-address
complete -c podman-create -l memory -s m
complete -c podman-create -l memory-reservation
complete -c podman-create -l memory-swap
complete -c podman-create -l memory-swappiness
complete -c podman-create -l mount
complete -c podman-create -l name
complete -c podman-create -l network -l net
complete -c podman-create -l no-map-gw -d 'container to host using the gateway address'
complete -c podman-create -s U -d host
complete -c podman-create -l network-alias
complete -c podman-create -l no-healthcheck
complete -c podman-create -l no-hosts
complete -c podman-create -l oom-kill-disable
complete -c podman-create -l oom-score-adj
complete -c podman-create -l os
complete -c podman-create -l passwd-entry
complete -c podman-create -l personality
complete -c podman-create -l pid
complete -c podman-create -l pidfile
complete -c podman-create -l pids-limit
complete -c podman-create -l platform
complete -c podman-create -l pod
complete -c podman-create -l pod-id-file
complete -c podman-create -l privileged
complete -c podman-create -l publish -s p
complete -c podman-create -l publish-all -s P
complete -c podman-create -l pull
complete -c podman-create -l quiet -s q
complete -c podman-create -l rdt-class
complete -c podman-create -l read-only
complete -c podman-create -l read-only-tmpfs
complete -c podman-create -l replace
complete -c podman-create -l requires
complete -c podman-create -l restart
complete -c podman-create -l rm
complete -c podman-create -l rootfs
complete -c podman-create -l sdnotify
complete -c podman-create -l seccomp-policy
complete -c podman-create -l secret
complete -c podman-create -l security-opt
complete -c podman-create -l shm-size
complete -c podman-create -l shm-size-systemd
complete -c podman-create -l stop-signal
complete -c podman-create -l stop-timeout
complete -c podman-create -l subgidname
complete -c podman-create -l subuidname
complete -c podman-create -l sysctl
complete -c podman-create -l systemd
complete -c podman-create -l timeout
complete -c podman-create -l tls-verify
complete -c podman-create -l tmpfs
complete -c podman-create -l tty -s t
complete -c podman-create -l tz
complete -c podman-create -l ulimit
complete -c podman-create -l umask
complete -c podman-create -l unsetenv
complete -c podman-create -l unsetenv-all
complete -c podman-create -l user -s u
complete -c podman-create -l userns
complete -c podman-create -l uts
complete -c podman-create -l variant
complete -c podman-create -l volume -s v
complete -c podman-create -l volumes-from
complete -c podman-create -l workdir -s w

