# podman-kill
# Autogenerated from man page /usr/share/man/man1/podman-kill.1.gz
complete -c podman-kill -l all -s a
complete -c podman-kill -l cidfile
complete -c podman-kill -l latest -s l
complete -c podman-kill -l signal -s s

