# podman-kube-generate
# Autogenerated from man page /usr/share/man/man1/podman-kube-generate.1.gz
complete -c podman-kube-generate -l filename -s f
complete -c podman-kube-generate -l no-trunc
complete -c podman-kube-generate -l podman-only
complete -c podman-kube-generate -l replicas -s r
complete -c podman-kube-generate -l service -s s
complete -c podman-kube-generate -l type -s t
complete -c podman-kube-generate -l - -d 'apiVersion: v1 kind: Service metadata:   creationTimestamp: 2018-12-18T15:16:…'

