# podman-auto-update
# Autogenerated from man page /usr/share/man/man1/podman-auto-update.1.gz
complete -c podman-auto-update -l authfile
complete -c podman-auto-update -l dry-run
complete -c podman-auto-update -l format
complete -c podman-auto-update -l rollback
complete -c podman-auto-update -l tls-verify

