# podman-rmi
# Autogenerated from man page /usr/share/man/man1/podman-rmi.1.gz
complete -c podman-rmi -l all -s a
complete -c podman-rmi -l force -s f
complete -c podman-rmi -l ignore -s i
complete -c podman-rmi -l no-prune

