# podman-login
# Autogenerated from man page /usr/share/man/man1/podman-login.1.gz
complete -c podman-login -l authfile
complete -c podman-login -l cert-dir
complete -c podman-login -l compat-auth-file
complete -c podman-login -l get-login
complete -c podman-login -l help -s h
complete -c podman-login -l password -s p
complete -c podman-login -l password-stdin
complete -c podman-login -l secret
complete -c podman-login -l tls-verify
complete -c podman-login -l username -s u
complete -c podman-login -l verbose -s v

