# podman-network-ls
# Autogenerated from man page /usr/share/man/man1/podman-network-ls.1.gz
complete -c podman-network-ls -l filter -s f
complete -c podman-network-ls -l format
complete -c podman-network-ls -l no-trunc
complete -c podman-network-ls -l noheading -s n
complete -c podman-network-ls -l quiet -s q

