# podman-pod-stats
# Autogenerated from man page /usr/share/man/man1/podman-pod-stats.1.gz
complete -c podman-pod-stats -l all -s a
complete -c podman-pod-stats -l format
complete -c podman-pod-stats -l latest -s l
complete -c podman-pod-stats -l no-reset
complete -c podman-pod-stats -l no-stream

