# podman-container-clone
# Autogenerated from man page /usr/share/man/man1/podman-container-clone.1.gz
complete -c podman-container-clone -l blkio-weight
complete -c podman-container-clone -l blkio-weight-device
complete -c podman-container-clone -l cpu-period
complete -c podman-container-clone -l cpu-quota
complete -c podman-container-clone -l cpu-rt-period
complete -c podman-container-clone -l cpu-rt-runtime
complete -c podman-container-clone -l cpu-shares -s c
complete -c podman-container-clone -l cpus
complete -c podman-container-clone -l cpuset-cpus
complete -c podman-container-clone -l cpuset-mems
complete -c podman-container-clone -l destroy
complete -c podman-container-clone -l device-read-bps
complete -c podman-container-clone -l device-write-bps
complete -c podman-container-clone -l force -s f
complete -c podman-container-clone -l memory -s m
complete -c podman-container-clone -l memory-reservation
complete -c podman-container-clone -l memory-swap
complete -c podman-container-clone -l memory-swappiness
complete -c podman-container-clone -l name
complete -c podman-container-clone -l pod
complete -c podman-container-clone -l run

