# podman-volume-rm
# Autogenerated from man page /usr/share/man/man1/podman-volume-rm.1.gz
complete -c podman-volume-rm -l all -s a
complete -c podman-volume-rm -l force -s f
complete -c podman-volume-rm -l help
complete -c podman-volume-rm -l time -s t

