# podman-run
# Autogenerated from man page /usr/share/man/man1/podman-run.1.gz
complete -c podman-run -l privileged -d 'container engine version, whether the engine is running in rootless mode, the…'
complete -c podman-run -l add-host
complete -c podman-run -l annotation
complete -c podman-run -l arch
complete -c podman-run -l attach -s a
complete -c podman-run -l authfile
complete -c podman-run -l blkio-weight
complete -c podman-run -l blkio-weight-device
complete -c podman-run -l cap-add
complete -c podman-run -l cap-drop
complete -c podman-run -l cgroup-conf
complete -c podman-run -l cgroup-parent
complete -c podman-run -l cgroupns
complete -c podman-run -l cgroups
complete -c podman-run -l chrootdirs
complete -c podman-run -l cidfile
complete -c podman-run -l conmon-pidfile
complete -c podman-run -l cpu-period
complete -c podman-run -l cpu-quota
complete -c podman-run -l cpu-rt-period
complete -c podman-run -l cpu-rt-runtime
complete -c podman-run -l cpu-shares -s c
complete -c podman-run -l cpus
complete -c podman-run -l cpuset-cpus
complete -c podman-run -l cpuset-mems
complete -c podman-run -l decryption-key
complete -c podman-run -l detach -s d
complete -c podman-run -l detach-keys
complete -c podman-run -l device
complete -c podman-run -l device-cgroup-rule
complete -c podman-run -l device-read-bps
complete -c podman-run -l device-read-iops
complete -c podman-run -l device-write-bps
complete -c podman-run -l device-write-iops
complete -c podman-run -l disable-content-trust
complete -c podman-run -l dns
complete -c podman-run -l dns-option
complete -c podman-run -l dns-search
complete -c podman-run -l entrypoint
complete -c podman-run -l env -s e
complete -c podman-run -l env-file
complete -c podman-run -l env-host
complete -c podman-run -l env-merge
complete -c podman-run -l expose
complete -c podman-run -l gidmap
complete -c podman-run -l uidmap -l uidmap -d 'Note: the --gidmap option cannot be called in conjunction with the --pod opti…'
complete -c podman-run -l group-add
complete -c podman-run -l group-entry
complete -c podman-run -l health-cmd
complete -c podman-run -l health-interval
complete -c podman-run -l health-on-failure
complete -c podman-run -l health-retries
complete -c podman-run -l health-start-period
complete -c podman-run -l health-startup-cmd
complete -c podman-run -l health-startup-interval
complete -c podman-run -l health-startup-retries
complete -c podman-run -l health-startup-success
complete -c podman-run -l health-startup-timeout
complete -c podman-run -l health-timeout
complete -c podman-run -l help
complete -c podman-run -l hostname -s h
complete -c podman-run -l hostuser
complete -c podman-run -l http-proxy
complete -c podman-run -l image-volume
complete -c podman-run -l init
complete -c podman-run -l init-path
complete -c podman-run -l interactive -s i
complete -c podman-run -l ip
complete -c podman-run -l ip6
complete -c podman-run -l ipc
complete -c podman-run -l label -s l
complete -c podman-run -l label-file
complete -c podman-run -l link-local-ip
complete -c podman-run -l log-driver
complete -c podman-run -l log-opt
complete -c podman-run -l mac-address
complete -c podman-run -l memory -s m
complete -c podman-run -l memory-reservation
complete -c podman-run -l memory-swap
complete -c podman-run -l memory-swappiness
complete -c podman-run -l mount
complete -c podman-run -l name
complete -c podman-run -l network -l net
complete -c podman-run -l no-map-gw -d 'container to host using the gateway address'
complete -c podman-run -s U -d host
complete -c podman-run -l network-alias
complete -c podman-run -l no-healthcheck
complete -c podman-run -l no-hosts
complete -c podman-run -l oom-kill-disable
complete -c podman-run -l oom-score-adj
complete -c podman-run -l os
complete -c podman-run -l passwd
complete -c podman-run -l passwd-entry
complete -c podman-run -l personality
complete -c podman-run -l pid
complete -c podman-run -l pidfile
complete -c podman-run -l pids-limit
complete -c podman-run -l platform
complete -c podman-run -l pod
complete -c podman-run -l pod-id-file
complete -c podman-run -l preserve-fds
complete -c podman-run -l publish -s p
complete -c podman-run -l publish-all -s P
complete -c podman-run -l pull
complete -c podman-run -l quiet -s q
complete -c podman-run -l rdt-class
complete -c podman-run -l read-only
complete -c podman-run -l read-only-tmpfs
complete -c podman-run -l replace
complete -c podman-run -l requires
complete -c podman-run -l restart
complete -c podman-run -l rm
complete -c podman-run -l rmi
complete -c podman-run -l rootfs
complete -c podman-run -l sdnotify
complete -c podman-run -l seccomp-policy
complete -c podman-run -l secret
complete -c podman-run -l security-opt
complete -c podman-run -l shm-size
complete -c podman-run -l shm-size-systemd
complete -c podman-run -l sig-proxy
complete -c podman-run -l stop-signal
complete -c podman-run -l stop-timeout
complete -c podman-run -l subgidname
complete -c podman-run -l subuidname
complete -c podman-run -l sysctl
complete -c podman-run -l systemd
complete -c podman-run -l timeout
complete -c podman-run -l tls-verify
complete -c podman-run -l tmpfs
complete -c podman-run -l tty -s t
complete -c podman-run -l tz
complete -c podman-run -l ulimit
complete -c podman-run -l umask
complete -c podman-run -l unsetenv
complete -c podman-run -l unsetenv-all
complete -c podman-run -l user -s u
complete -c podman-run -l userns
complete -c podman-run -l uts
complete -c podman-run -l variant
complete -c podman-run -l volume -s v
complete -c podman-run -l volumes-from
complete -c podman-run -l workdir -s w
complete -c podman-run -l ---- -l ------ -d 'key        shmid      owner      perms      bytes      nattch     status 0x01…'
complete -c podman-run -l permissive

