# podman-manifest-create
# Autogenerated from man page /usr/share/man/man1/podman-manifest-create.1.gz
complete -c podman-manifest-create -l all
complete -c podman-manifest-create -l amend -s a
complete -c podman-manifest-create -l tls-verify

