# podman-network-create
# Autogenerated from man page /usr/share/man/man1/podman-network-create.1.gz
complete -c podman-network-create -l disable-dns
complete -c podman-network-create -l dns
complete -c podman-network-create -l driver -s d
complete -c podman-network-create -l gateway
complete -c podman-network-create -l ignore
complete -c podman-network-create -l interface-name
complete -c podman-network-create -l internal
complete -c podman-network-create -l ip-range
complete -c podman-network-create -l ipam-driver
complete -c podman-network-create -l ipv6
complete -c podman-network-create -l label
complete -c podman-network-create -l opt -s o
complete -c podman-network-create -l route
complete -c podman-network-create -l subnet

