# podman-kube-play
# Autogenerated from man page /usr/share/man/man1/podman-kube-play.1.gz
complete -c podman-kube-play -l - -d 'apiVersion: v1 kind: Pod metadata:   name: foobar spec:   containers:   - nam…'
complete -c podman-kube-play -l annotation
complete -c podman-kube-play -l authfile
complete -c podman-kube-play -l build
complete -c podman-kube-play -l cert-dir
complete -c podman-kube-play -l configmap
complete -c podman-kube-play -l context-dir
complete -c podman-kube-play -l creds
complete -c podman-kube-play -l force
complete -c podman-kube-play -l help -s h
complete -c podman-kube-play -l ip
complete -c podman-kube-play -l log-driver
complete -c podman-kube-play -l log-opt
complete -c podman-kube-play -l mac-address
complete -c podman-kube-play -l network -l net
complete -c podman-kube-play -l no-map-gw -d 'container to host using the gateway address'
complete -c podman-kube-play -s U -d host
complete -c podman-kube-play -l no-hosts
complete -c podman-kube-play -l no-trunc
complete -c podman-kube-play -l publish
complete -c podman-kube-play -l publish-all
complete -c podman-kube-play -l quiet -s q
complete -c podman-kube-play -l replace
complete -c podman-kube-play -l seccomp-profile-root
complete -c podman-kube-play -l start
complete -c podman-kube-play -l tls-verify
complete -c podman-kube-play -l userns
complete -c podman-kube-play -l pod
complete -c podman-kube-play -l wait -s w

