# podman-manifest-annotate
# Autogenerated from man page /usr/share/man/man1/podman-manifest-annotate.1.gz
complete -c podman-manifest-annotate -l annotation
complete -c podman-manifest-annotate -l arch
complete -c podman-manifest-annotate -l features
complete -c podman-manifest-annotate -l os
complete -c podman-manifest-annotate -l os-features
complete -c podman-manifest-annotate -l os-version
complete -c podman-manifest-annotate -l variant

