# podman-image-prune
# Autogenerated from man page /usr/share/man/man1/podman-image-prune.1.gz
complete -c podman-image-prune -l all -s a
complete -c podman-image-prune -l external
complete -c podman-image-prune -l filter
complete -c podman-image-prune -l force -s f
complete -c podman-image-prune -l help -s h

