# podman-machine-set
# Autogenerated from man page /usr/share/man/man1/podman-machine-set.1.gz
complete -c podman-machine-set -l cpus
complete -c podman-machine-set -l disk-size
complete -c podman-machine-set -l help
complete -c podman-machine-set -l memory -s m
complete -c podman-machine-set -l rootful
complete -c podman-machine-set -l usb
complete -c podman-machine-set -l user-mode-networking

