# podman-stats
# Autogenerated from man page /usr/share/man/man1/podman-stats.1.gz
complete -c podman-stats -l all -s a
complete -c podman-stats -l format
complete -c podman-stats -l interval -s i
complete -c podman-stats -l latest -s l
complete -c podman-stats -l no-reset
complete -c podman-stats -l no-stream
complete -c podman-stats -l no-trunc

