# podman-generate-spec
# Autogenerated from man page /usr/share/man/man1/podman-generate-spec.1.gz
complete -c podman-generate-spec -l compact -s c
complete -c podman-generate-spec -l filename -s f
complete -c podman-generate-spec -l name -s n

