# podman-pod-ps
# Autogenerated from man page /usr/share/man/man1/podman-pod-ps.1.gz
complete -c podman-pod-ps -l ctr-ids
complete -c podman-pod-ps -l ctr-names
complete -c podman-pod-ps -l ctr-status
complete -c podman-pod-ps -l filter -s f
complete -c podman-pod-ps -l format
complete -c podman-pod-ps -l help -s h
complete -c podman-pod-ps -l latest -s l
complete -c podman-pod-ps -l namespace -l ns
complete -c podman-pod-ps -l no-trunc
complete -c podman-pod-ps -l noheading -s n
complete -c podman-pod-ps -l quiet -s q
complete -c podman-pod-ps -l sort

