# podman-search
# Autogenerated from man page /usr/share/man/man1/podman-search.1.gz
complete -c podman-search -l authfile
complete -c podman-search -l cert-dir
complete -c podman-search -l compatible
complete -c podman-search -l creds
complete -c podman-search -l filter -s f
complete -c podman-search -l format
complete -c podman-search -l help -s h
complete -c podman-search -l limit
complete -c podman-search -l list-tags
complete -c podman-search -l no-trunc
complete -c podman-search -l tls-verify

