# podman-machine-start
# Autogenerated from man page /usr/share/man/man1/podman-machine-start.1.gz
complete -c podman-machine-start -l help
complete -c podman-machine-start -l no-info
complete -c podman-machine-start -l quiet -s q

