# podman-machine-list
# Autogenerated from man page /usr/share/man/man1/podman-machine-list.1.gz
complete -c podman-machine-list -l format
complete -c podman-machine-list -l help
complete -c podman-machine-list -l noheading -s n
complete -c podman-machine-list -l quiet -s q

