# podman-kube-apply
# Autogenerated from man page /usr/share/man/man1/podman-kube-apply.1.gz
complete -c podman-kube-apply -l ca-cert-file
complete -c podman-kube-apply -l file -s f
complete -c podman-kube-apply -l kubeconfig -s k
complete -c podman-kube-apply -l ns
complete -c podman-kube-apply -l service -s s

