# podman-machine-init
# Autogenerated from man page /usr/share/man/man1/podman-machine-init.1.gz
complete -c podman-machine-init -l cpus
complete -c podman-machine-init -l disk-size
complete -c podman-machine-init -l help
complete -c podman-machine-init -l ignition-path
complete -c podman-machine-init -l image-path
complete -c podman-machine-init -l memory -s m
complete -c podman-machine-init -l now
complete -c podman-machine-init -l rootful
complete -c podman-machine-init -l timezone
complete -c podman-machine-init -l usb
complete -c podman-machine-init -l user-mode-networking
complete -c podman-machine-init -l username
complete -c podman-machine-init -l volume -s v
complete -c podman-machine-init -l volume-driver

