# podman-logs
# Autogenerated from man page /usr/share/man/man1/podman-logs.1.gz
complete -c podman-logs -l color
complete -c podman-logs -l follow -s f
complete -c podman-logs -l latest -s l
complete -c podman-logs -l names -s n
complete -c podman-logs -l since
complete -c podman-logs -l tail
complete -c podman-logs -l timestamps -s t
complete -c podman-logs -l until

