# podman-images
# Autogenerated from man page /usr/share/man/man1/podman-images.1.gz
complete -c podman-images -l all -s a
complete -c podman-images -l digests
complete -c podman-images -l filter -s f
complete -c podman-images -l format
complete -c podman-images -l history
complete -c podman-images -l no-trunc
complete -c podman-images -l noheading -s n
complete -c podman-images -l quiet -s q
complete -c podman-images -l sort

