# podman-pause
# Autogenerated from man page /usr/share/man/man1/podman-pause.1.gz
complete -c podman-pause -l all -s a
complete -c podman-pause -l cidfile
complete -c podman-pause -l filter -s f
complete -c podman-pause -l latest -s l

