# podman-import
# Autogenerated from man page /usr/share/man/man1/podman-import.1.gz
complete -c podman-import -l arch
complete -c podman-import -l change -s c
complete -c podman-import -l help -s h
complete -c podman-import -l message -s m
complete -c podman-import -l os
complete -c podman-import -l quiet -s q
complete -c podman-import -l variant

