# podman-container-cleanup
# Autogenerated from man page /usr/share/man/man1/podman-container-cleanup.1.gz
complete -c podman-container-cleanup -l all -s a
complete -c podman-container-cleanup -l exec
complete -c podman-container-cleanup -l latest -s l
complete -c podman-container-cleanup -l rm
complete -c podman-container-cleanup -l rmi

