# podman-secret-ls
# Autogenerated from man page /usr/share/man/man1/podman-secret-ls.1.gz
complete -c podman-secret-ls -l filter -s f
complete -c podman-secret-ls -l format
complete -c podman-secret-ls -l noheading -s n
complete -c podman-secret-ls -l quiet -s q

