# podman-inspect
# Autogenerated from man page /usr/share/man/man1/podman-inspect.1.gz
complete -c podman-inspect -l format -s f
complete -c podman-inspect -l latest -s l
complete -c podman-inspect -l size -s s
complete -c podman-inspect -l type -s t

