# podman-image-sign
# Autogenerated from man page /usr/share/man/man1/podman-image-sign.1.gz
complete -c podman-image-sign -l all -s a
complete -c podman-image-sign -l authfile
complete -c podman-image-sign -l cert-dir
complete -c podman-image-sign -l directory -s d
complete -c podman-image-sign -l help -s h
complete -c podman-image-sign -l sign-by

