# podman-exec
# Autogenerated from man page /usr/share/man/man1/podman-exec.1.gz
complete -c podman-exec -l detach -s d
complete -c podman-exec -l detach-keys
complete -c podman-exec -l env -s e
complete -c podman-exec -l env-file
complete -c podman-exec -l interactive -s i
complete -c podman-exec -l latest -s l
complete -c podman-exec -l preserve-fds
complete -c podman-exec -l privileged
complete -c podman-exec -l tty -s t
complete -c podman-exec -l user -s u
complete -c podman-exec -l workdir -s w

