# podman-generate-systemd
# Autogenerated from man page /usr/share/man/man1/podman-generate-systemd.1.gz
complete -c podman-generate-systemd -l after
complete -c podman-generate-systemd -l container-prefix
complete -c podman-generate-systemd -l env -s e
complete -c podman-generate-systemd -l files -s f
complete -c podman-generate-systemd -l format
complete -c podman-generate-systemd -l name -s n
complete -c podman-generate-systemd -l new
complete -c podman-generate-systemd -l no-header
complete -c podman-generate-systemd -l pod-prefix
complete -c podman-generate-systemd -l requires
complete -c podman-generate-systemd -l restart-policy
complete -c podman-generate-systemd -l restart-sec
complete -c podman-generate-systemd -l separator
complete -c podman-generate-systemd -l start-timeout
complete -c podman-generate-systemd -l stop-timeout
complete -c podman-generate-systemd -l template
complete -c podman-generate-systemd -l wants

