# podman-secret-create
# Autogenerated from man page /usr/share/man/man1/podman-secret-create.1.gz
complete -c podman-secret-create -l driver -s d
complete -c podman-secret-create -l driver-opts
complete -c podman-secret-create -l env
complete -c podman-secret-create -l help
complete -c podman-secret-create -l label -s l
complete -c podman-secret-create -l replace

