# podman-pod-rm
# Autogenerated from man page /usr/share/man/man1/podman-pod-rm.1.gz
complete -c podman-pod-rm -l all -s a
complete -c podman-pod-rm -l force -s f
complete -c podman-pod-rm -l ignore -s i
complete -c podman-pod-rm -l latest -s l
complete -c podman-pod-rm -l pod-id-file
complete -c podman-pod-rm -l time -s t

