# podman-secret-inspect
# Autogenerated from man page /usr/share/man/man1/podman-secret-inspect.1.gz
complete -c podman-secret-inspect -l format -s f
complete -c podman-secret-inspect -l help
complete -c podman-secret-inspect -l pretty
complete -c podman-secret-inspect -l showsecret

