# podman-events
# Autogenerated from man page /usr/share/man/man1/podman-events.1.gz
complete -c podman-events -l filter -s f
complete -c podman-events -l format
complete -c podman-events -l help
complete -c podman-events -l no-trunc
complete -c podman-events -l since
complete -c podman-events -l stream
complete -c podman-events -l until

