# podman-container-inspect
# Autogenerated from man page /usr/share/man/man1/podman-container-inspect.1.gz
complete -c podman-container-inspect -l format -s f
complete -c podman-container-inspect -l latest -s l
complete -c podman-container-inspect -l size -s s

