# podman-logout
# Autogenerated from man page /usr/share/man/man1/podman-logout.1.gz
complete -c podman-logout -l all -s a
complete -c podman-logout -l authfile
complete -c podman-logout -l compat-auth-file
complete -c podman-logout -l help -s h

