# podman-volume-ls
# Autogenerated from man page /usr/share/man/man1/podman-volume-ls.1.gz
complete -c podman-volume-ls -l filter -s f
complete -c podman-volume-ls -l format
complete -c podman-volume-ls -l help
complete -c podman-volume-ls -l noheading -s n
complete -c podman-volume-ls -l quiet -s q

