# podman-manifest-add
# Autogenerated from man page /usr/share/man/man1/podman-manifest-add.1.gz
complete -c podman-manifest-add -l all
complete -c podman-manifest-add -l annotation
complete -c podman-manifest-add -l arch
complete -c podman-manifest-add -l authfile
complete -c podman-manifest-add -l cert-dir
complete -c podman-manifest-add -l creds
complete -c podman-manifest-add -l features
complete -c podman-manifest-add -l os
complete -c podman-manifest-add -l os-version
complete -c podman-manifest-add -l tls-verify
complete -c podman-manifest-add -l variant

