# podman-attach
# Autogenerated from man page /usr/share/man/man1/podman-attach.1.gz
complete -c podman-attach -l detach-keys
complete -c podman-attach -l latest -s l
complete -c podman-attach -l no-stdin
complete -c podman-attach -l sig-proxy

