# podman-unmount
# Autogenerated from man page /usr/share/man/man1/podman-unmount.1.gz
complete -c podman-unmount -l all -s a
complete -c podman-unmount -l force -s f
complete -c podman-unmount -l latest -s l

