# podman-container-restore
# Autogenerated from man page /usr/share/man/man1/podman-container-restore.1.gz
complete -c podman-container-restore -l all -s a
complete -c podman-container-restore -l file-locks
complete -c podman-container-restore -l ignore-rootfs
complete -c podman-container-restore -l ignore-static-ip
complete -c podman-container-restore -l ignore-static-mac
complete -c podman-container-restore -l ignore-volumes
complete -c podman-container-restore -l import -s i
complete -c podman-container-restore -l import-previous
complete -c podman-container-restore -l keep -s k
complete -c podman-container-restore -l latest -s l
complete -c podman-container-restore -l name -s n
complete -c podman-container-restore -l pod
complete -c podman-container-restore -l print-stats
complete -c podman-container-restore -l publish -s p
complete -c podman-container-restore -l tcp-established

