# podman-unpause
# Autogenerated from man page /usr/share/man/man1/podman-unpause.1.gz
complete -c podman-unpause -l all -s a
complete -c podman-unpause -l cidfile
complete -c podman-unpause -l filter -s f
complete -c podman-unpause -l latest -s l

