# podman-pod-stop
# Autogenerated from man page /usr/share/man/man1/podman-pod-stop.1.gz
complete -c podman-pod-stop -l all -s a
complete -c podman-pod-stop -l ignore -s i
complete -c podman-pod-stop -l latest -s l
complete -c podman-pod-stop -l pod-id-file
complete -c podman-pod-stop -l time -s t

