# podman-ps
# Autogenerated from man page /usr/share/man/man1/podman-ps.1.gz
complete -c podman-ps -l all -s a
complete -c podman-ps -l external
complete -c podman-ps -l filter -s f
complete -c podman-ps -l format
complete -c podman-ps -l help -s h
complete -c podman-ps -l last -s n
complete -c podman-ps -l latest -s l
complete -c podman-ps -l namespace -l ns
complete -c podman-ps -l no-trunc
complete -c podman-ps -l noheading
complete -c podman-ps -l pod -s p
complete -c podman-ps -l quiet -s q
complete -c podman-ps -l size -s s
complete -c podman-ps -l sort
complete -c podman-ps -l sync
complete -c podman-ps -l watch -s w

