# podman-pod-clone
# Autogenerated from man page /usr/share/man/man1/podman-pod-clone.1.gz
complete -c podman-pod-clone -l blkio-weight
complete -c podman-pod-clone -l blkio-weight-device
complete -c podman-pod-clone -l cgroup-parent
complete -c podman-pod-clone -l cpu-shares -s c
complete -c podman-pod-clone -l cpus
complete -c podman-pod-clone -l cpuset-cpus
complete -c podman-pod-clone -l cpuset-mems
complete -c podman-pod-clone -l destroy
complete -c podman-pod-clone -l device
complete -c podman-pod-clone -l device-read-bps
complete -c podman-pod-clone -l device-write-bps
complete -c podman-pod-clone -l gidmap
complete -c podman-pod-clone -l help -s h
complete -c podman-pod-clone -l hostname
complete -c podman-pod-clone -l infra-command
complete -c podman-pod-clone -l infra-conmon-pidfile
complete -c podman-pod-clone -l infra-name
complete -c podman-pod-clone -l label -s l
complete -c podman-pod-clone -l label-file
complete -c podman-pod-clone -l memory -s m
complete -c podman-pod-clone -l memory-swap
complete -c podman-pod-clone -l name -s n
complete -c podman-pod-clone -l pid
complete -c podman-pod-clone -l restart
complete -c podman-pod-clone -l security-opt
complete -c podman-pod-clone -l shm-size
complete -c podman-pod-clone -l shm-size-systemd
complete -c podman-pod-clone -l start
complete -c podman-pod-clone -l subgidname
complete -c podman-pod-clone -l subuidname
complete -c podman-pod-clone -l sysctl
complete -c podman-pod-clone -l uidmap
complete -c podman-pod-clone -l userns
complete -c podman-pod-clone -l uts
complete -c podman-pod-clone -l volume -s v
complete -c podman-pod-clone -l volumes-from

