# podman-pod-create
# Autogenerated from man page /usr/share/man/man1/podman-pod-create.1.gz
complete -c podman-pod-create -l add-host
complete -c podman-pod-create -l blkio-weight
complete -c podman-pod-create -l blkio-weight-device
complete -c podman-pod-create -l cgroup-parent
complete -c podman-pod-create -l cpu-shares -s c
complete -c podman-pod-create -l cpus
complete -c podman-pod-create -l cpuset-cpus
complete -c podman-pod-create -l cpuset-mems
complete -c podman-pod-create -l device
complete -c podman-pod-create -l device-read-bps
complete -c podman-pod-create -l device-write-bps
complete -c podman-pod-create -l dns
complete -c podman-pod-create -l dns-option
complete -c podman-pod-create -l dns-search
complete -c podman-pod-create -l exit-policy
complete -c podman-pod-create -l gidmap
complete -c podman-pod-create -l help -s h
complete -c podman-pod-create -l hostname
complete -c podman-pod-create -l infra
complete -c podman-pod-create -l infra-command
complete -c podman-pod-create -l infra-conmon-pidfile
complete -c podman-pod-create -l infra-image
complete -c podman-pod-create -l infra-name
complete -c podman-pod-create -l ip
complete -c podman-pod-create -l ip6
complete -c podman-pod-create -l label -s l
complete -c podman-pod-create -l label-file
complete -c podman-pod-create -l mac-address
complete -c podman-pod-create -l memory -s m
complete -c podman-pod-create -l memory-swap
complete -c podman-pod-create -l name -s n
complete -c podman-pod-create -l network -l net
complete -c podman-pod-create -l no-map-gw -d 'container to host using the gateway address'
complete -c podman-pod-create -s U -d host
complete -c podman-pod-create -l network-alias
complete -c podman-pod-create -l no-hosts
complete -c podman-pod-create -l pid
complete -c podman-pod-create -l pod-id-file
complete -c podman-pod-create -l publish -s p
complete -c podman-pod-create -l replace
complete -c podman-pod-create -l restart
complete -c podman-pod-create -l security-opt
complete -c podman-pod-create -l share
complete -c podman-pod-create -l share-parent
complete -c podman-pod-create -l shm-size
complete -c podman-pod-create -l shm-size-systemd
complete -c podman-pod-create -l subgidname
complete -c podman-pod-create -l subuidname
complete -c podman-pod-create -l sysctl
complete -c podman-pod-create -l uidmap
complete -c podman-pod-create -l userns
complete -c podman-pod-create -l uts
complete -c podman-pod-create -l volume -s v
complete -c podman-pod-create -l volumes-from

