# podman-wait
# Autogenerated from man page /usr/share/man/man1/podman-wait.1.gz
complete -c podman-wait -l condition
complete -c podman-wait -l help -s h
complete -c podman-wait -l ignore
complete -c podman-wait -l interval -s i
complete -c podman-wait -l latest -s l
complete -c podman-wait -s 1 -d 'SEE ALSO'

