# podman-system-connection-add
# Autogenerated from man page /usr/share/man/man1/podman-system-connection-add.1.gz
complete -c podman-system-connection-add -l default -s d
complete -c podman-system-connection-add -l identity
complete -c podman-system-connection-add -l port -s p
complete -c podman-system-connection-add -l socket-path

