# podman-image-trust
# Autogenerated from man page /usr/share/man/man1/podman-image-trust.1.gz
complete -c podman-image-trust -l help -s h
complete -c podman-image-trust -l pubkeysfile -s f
complete -c podman-image-trust -l type -s t
complete -c podman-image-trust -l json -s j
complete -c podman-image-trust -l noheading -s n
complete -c podman-image-trust -l raw

