# podman-manifest-inspect
# Autogenerated from man page /usr/share/man/man1/podman-manifest-inspect.1.gz
complete -c podman-manifest-inspect -l authfile
complete -c podman-manifest-inspect -l tls-verify

