# podman-history
# Autogenerated from man page /usr/share/man/man1/podman-history.1.gz
complete -c podman-history -l format
complete -c podman-history -l help -s h
complete -c podman-history -l human -s H
complete -c podman-history -l no-trunc
complete -c podman-history -l quiet -s q

