# podman-machine-rm
# Autogenerated from man page /usr/share/man/man1/podman-machine-rm.1.gz
complete -c podman-machine-rm -l force -s f
complete -c podman-machine-rm -l help
complete -c podman-machine-rm -l save-ignition
complete -c podman-machine-rm -l save-image
complete -c podman-machine-rm -l save-keys

