# podman-farm-build
# Autogenerated from man page /usr/share/man/man1/podman-farm-build.1.gz
complete -c podman-farm-build -l tag
complete -c podman-farm-build -l add-host
complete -c podman-farm-build -l annotation
complete -c podman-farm-build -l authfile
complete -c podman-farm-build -l build-arg
complete -c podman-farm-build -l build-arg-file
complete -c podman-farm-build -l build-context
complete -c podman-farm-build -l cache-from
complete -c podman-farm-build -l cache-to
complete -c podman-farm-build -l cache-ttl
complete -c podman-farm-build -l cap-add
complete -c podman-farm-build -l cap-drop
complete -c podman-farm-build -l cert-dir
complete -c podman-farm-build -l cgroup-parent
complete -c podman-farm-build -l cgroupns
complete -c podman-farm-build -l cleanup
complete -c podman-farm-build -l cpp-flag
complete -c podman-farm-build -l cpu-period
complete -c podman-farm-build -l cpu-quota
complete -c podman-farm-build -l cpu-shares -s c
complete -c podman-farm-build -l cpuset-cpus
complete -c podman-farm-build -l cpuset-mems
complete -c podman-farm-build -l creds
complete -c podman-farm-build -l decryption-key
complete -c podman-farm-build -l device
complete -c podman-farm-build -l disable-compression -s D
complete -c podman-farm-build -l dns
complete -c podman-farm-build -l dns-option
complete -c podman-farm-build -l dns-search
complete -c podman-farm-build -l env
complete -c podman-farm-build -l farm
complete -c podman-farm-build -l file -s f
complete -c podman-farm-build -l force-rm
complete -c podman-farm-build -l format
complete -c podman-farm-build -l from
complete -c podman-farm-build -l group-add
complete -c podman-farm-build -l help -s h
complete -c podman-farm-build -l hooks-dir
complete -c podman-farm-build -l http-proxy
complete -c podman-farm-build -l identity-label
complete -c podman-farm-build -l ignorefile
complete -c podman-farm-build -l iidfile
complete -c podman-farm-build -l ipc
complete -c podman-farm-build -l isolation
complete -c podman-farm-build -l no-pivot -d 'disabled, and IPC, PID, and user namespaces enabled; the default for unprivil…'
complete -c podman-farm-build -l jobs
complete -c podman-farm-build -l label
complete -c podman-farm-build -l layer-label
complete -c podman-farm-build -l layers
complete -c podman-farm-build -l local -s l
complete -c podman-farm-build -l logfile
complete -c podman-farm-build -l memory -s m
complete -c podman-farm-build -l memory-swap
complete -c podman-farm-build -l network -l net
complete -c podman-farm-build -l no-map-gw -d 'container to host using the gateway address'
complete -c podman-farm-build -s U -d host
complete -c podman-farm-build -l no-cache
complete -c podman-farm-build -l no-hostname
complete -c podman-farm-build -l no-hosts
complete -c podman-farm-build -l omit-history
complete -c podman-farm-build -l os-feature
complete -c podman-farm-build -l os-version
complete -c podman-farm-build -l pid
complete -c podman-farm-build -l platforms
complete -c podman-farm-build -l pull
complete -c podman-farm-build -l quiet -s q
complete -c podman-farm-build -l retry
complete -c podman-farm-build -l retry-delay
complete -c podman-farm-build -l rm
complete -c podman-farm-build -l runtime
complete -c podman-farm-build -l runtime-flag
complete -c podman-farm-build -l secret
complete -c podman-farm-build -l security-opt
complete -c podman-farm-build -l shm-size
complete -c podman-farm-build -l skip-unused-stages
complete -c podman-farm-build -l squash
complete -c podman-farm-build -l squash-all
complete -c podman-farm-build -l ssh
complete -c podman-farm-build -s t
complete -c podman-farm-build -l target
complete -c podman-farm-build -l timestamp
complete -c podman-farm-build -l tls-verify
complete -c podman-farm-build -l ulimit
complete -c podman-farm-build -l unsetenv
complete -c podman-farm-build -l unsetlabel
complete -c podman-farm-build -l userns
complete -c podman-farm-build -l userns-gid-map
complete -c podman-farm-build -l userns-gid-map-group
complete -c podman-farm-build -l userns-uid-map
complete -c podman-farm-build -l userns-uid-map-user
complete -c podman-farm-build -l uts
complete -c podman-farm-build -l volume -s v

