# podman-farm-update
# Autogenerated from man page /usr/share/man/man1/podman-farm-update.1.gz
complete -c podman-farm-update -l add -s a
complete -c podman-farm-update -l default -s d
complete -c podman-farm-update -l remove -s r

