# podman-push
# Autogenerated from man page /usr/share/man/man1/podman-push.1.gz
complete -c podman-push -l authfile
complete -c podman-push -l cert-dir
complete -c podman-push -l compress
complete -c podman-push -l compression-format
complete -c podman-push -l compression-level
complete -c podman-push -l creds
complete -c podman-push -l digestfile
complete -c podman-push -l disable-content-trust
complete -c podman-push -l encrypt-layer
complete -c podman-push -l encryption-key
complete -c podman-push -l force-compression
complete -c podman-push -l format -s f
complete -c podman-push -l quiet -s q
complete -c podman-push -l remove-signatures
complete -c podman-push -l sign-by
complete -c podman-push -l sign-by-sigstore
complete -c podman-push -l sign-by-sigstore-private-key
complete -c podman-push -l sign-passphrase-file
complete -c podman-push -l tls-verify

