# podman-container-runlabel
# Autogenerated from man page /usr/share/man/man1/podman-container-runlabel.1.gz
complete -c podman-container-runlabel -l authfile
complete -c podman-container-runlabel -l cert-dir
complete -c podman-container-runlabel -l creds
complete -c podman-container-runlabel -l display
complete -c podman-container-runlabel -l help -s h
complete -c podman-container-runlabel -l name -s n
complete -c podman-container-runlabel -l quiet -s q
complete -c podman-container-runlabel -l replace
complete -c podman-container-runlabel -l tls-verify

