# podman-system-connection-list
# Autogenerated from man page /usr/share/man/man1/podman-system-connection-list.1.gz
complete -c podman-system-connection-list -l format -s f
complete -c podman-system-connection-list -l quiet -s q

