# podman-pod-logs
# Autogenerated from man page /usr/share/man/man1/podman-pod-logs.1.gz
complete -c podman-pod-logs -l color
complete -c podman-pod-logs -l container -s c
complete -c podman-pod-logs -l follow -s f
complete -c podman-pod-logs -l latest -s l
complete -c podman-pod-logs -l names -s n
complete -c podman-pod-logs -l since
complete -c podman-pod-logs -l tail
complete -c podman-pod-logs -l timestamps -s t
complete -c podman-pod-logs -l until

