# podman-save
# Autogenerated from man page /usr/share/man/man1/podman-save.1.gz
complete -c podman-save -l compress
complete -c podman-save -l format
complete -c podman-save -l help -s h
complete -c podman-save -l multi-image-archive -s m
complete -c podman-save -l output -s o
complete -c podman-save -l quiet -s q
complete -c podman-save -l uncompressed

