# podman-pull
# Autogenerated from man page /usr/share/man/man1/podman-pull.1.gz
complete -c podman-pull -l all-tags -s a
complete -c podman-pull -l arch
complete -c podman-pull -l authfile
complete -c podman-pull -l cert-dir
complete -c podman-pull -l creds
complete -c podman-pull -l decryption-key
complete -c podman-pull -l disable-content-trust
complete -c podman-pull -l help -s h
complete -c podman-pull -l os
complete -c podman-pull -l platform
complete -c podman-pull -l quiet -s q
complete -c podman-pull -l tls-verify
complete -c podman-pull -l variant

