# podman-container-checkpoint
# Autogenerated from man page /usr/share/man/man1/podman-container-checkpoint.1.gz
complete -c podman-container-checkpoint -l all -s a
complete -c podman-container-checkpoint -l compress -s c
complete -c podman-container-checkpoint -l create-image
complete -c podman-container-checkpoint -l export -s e
complete -c podman-container-checkpoint -l file-locks
complete -c podman-container-checkpoint -l ignore-rootfs
complete -c podman-container-checkpoint -l ignore-volumes
complete -c podman-container-checkpoint -l keep -s k
complete -c podman-container-checkpoint -l latest -s l
complete -c podman-container-checkpoint -l leave-running -s R
complete -c podman-container-checkpoint -l pre-checkpoint -s P
complete -c podman-container-checkpoint -l print-stats
complete -c podman-container-checkpoint -l tcp-established
complete -c podman-container-checkpoint -l with-previous

