# podman-update
# Autogenerated from man page /usr/share/man/man1/podman-update.1.gz
complete -c podman-update -l blkio-weight
complete -c podman-update -l blkio-weight-device
complete -c podman-update -l cpu-period
complete -c podman-update -l cpu-quota
complete -c podman-update -l cpu-rt-period
complete -c podman-update -l cpu-rt-runtime
complete -c podman-update -l cpu-shares -s c
complete -c podman-update -l cpus
complete -c podman-update -l cpuset-cpus
complete -c podman-update -l cpuset-mems
complete -c podman-update -l device-read-bps
complete -c podman-update -l device-read-iops
complete -c podman-update -l device-write-bps
complete -c podman-update -l device-write-iops
complete -c podman-update -l memory -s m
complete -c podman-update -l memory-reservation
complete -c podman-update -l memory-swap
complete -c podman-update -l memory-swappiness
complete -c podman-update -l pids-limit

