# sealert
# Autogenerated from man page /usr/share/man/man8/sealert.8.gz
complete -c sealert -s b -l browser -d 'Launch the browser'
complete -c sealert -s f -l fix -d 'Execute the fix command for the avc with the given uuid and plugin, requires …'
complete -c sealert -s h -l help -d 'Show this message'
complete -c sealert -s s -l service -d 'Start sealert service,  Usually used by dbus'
complete -c sealert -s S -l noservice -d 'Start sealert without dbus service as stand alone app'
complete -c sealert -s l -l lookupid -d 'Lookup alert by id, if id is wildcard * then return all alerts'
complete -c sealert -s a -l analyze -d 'Scan a log file, analyze its AVCs'
complete -c sealert -s u -l user -d 'logon as user'
complete -c sealert -s p -l password -d 'set user password'

