# setroubleshootd
# Autogenerated from man page /usr/share/man/man8/setroubleshootd.8.gz
complete -c setroubleshootd -s f -l nofork -d 'Do not fork the daemon'
complete -c setroubleshootd -s d -l debug -d 'Do not exit after 10 seconds of inactivity'
complete -c setroubleshootd -s h -l help -d 'Show this message'

