# translit
# Autogenerated from man page /usr/share/man/man1/translit.1.gz
complete -c translit -l trans -s t
complete -c translit -l reverse -s r
complete -c translit -l list
complete -c translit -l infile -s i
complete -c translit -l outfile -s o
complete -c translit -s l
complete -c translit -l verbose -s v
complete -c translit -l help -s h

