# youtube-dl
# Autogenerated from man page /usr/share/man/man1/youtube-dl.1.gz
complete -c youtube-dl -s h -d 'Print this help text and exit'
complete -c youtube-dl -s U -d 'Update this program to latest version'
complete -c youtube-dl -s i -d 'Continue on download errors, for example to skip unavailable videos in a play…'
complete -c youtube-dl -s 4 -d 'Make all connections via IPv4'
complete -c youtube-dl -s 6 -d 'Make all connections via IPv6 . SS Geo Restriction:'
complete -c youtube-dl -s r -d 'Maximum download rate in bytes per second (e. g. 50K or 4. 2M)'
complete -c youtube-dl -s R -d 'Number of retries (default is 10), or \\[lq]infinite\\[rq]'
complete -c youtube-dl -s a -d 'File containing URLs to download (`-\' for stdin), one URL per line'
complete -c youtube-dl -s o -d 'Output filename template, see the \\[lq]OUTPUT TEMPLATE\\[rq] for all the info'
complete -c youtube-dl -s w -d 'Do not overwrite files'
complete -c youtube-dl -s c -d 'Force resume of partially downloaded files'
complete -c youtube-dl -s q -d 'Activate quiet mode'
complete -c youtube-dl -s s -d 'Do not download the video and do not write anything to disk'
complete -c youtube-dl -s g -d 'Simulate, quiet but print URL'
complete -c youtube-dl -s e -d 'Simulate, quiet but print title'
complete -c youtube-dl -s j -d 'Simulate, quiet but print JSON information'
complete -c youtube-dl -s J -d 'Simulate, quiet but print JSON information for each command-line argument'
complete -c youtube-dl -s v -d 'Print various debugging information'
complete -c youtube-dl -s C -d 'Contact the youtube-dl server for debugging'
complete -c youtube-dl -s f -d 'Video format code, see the \\[lq]FORMAT SELECTION\\[rq] for all the info'
complete -c youtube-dl -s F -d 'List all available formats of requested videos'
complete -c youtube-dl -s u -d 'Login with this account ID'
complete -c youtube-dl -s p -d 'Account password'
complete -c youtube-dl -s 2 -d 'Two-factor authentication code'
complete -c youtube-dl -s n -d 'Use . netrc authentication data'
complete -c youtube-dl -s x -d 'Convert video files to audio-only files (requires ffmpeg/avconv and ffprobe/a…'
complete -c youtube-dl -s k -d 'Keep the video file on disk after the post-processing; the video is erased by…'
complete -c youtube-dl -l no-mtime
complete -c youtube-dl -l proxy
complete -c youtube-dl -l format -d '[bu] 2 format_note (string): Additional info about the format [bu] 2 width (n…'
complete -c youtube-dl -l output-na-placeholder
complete -c youtube-dl -l date -l datebefore -l dateafter -d 'They accept dates in two formats: [bu] 2 Absolute dates: Dates in the format …'
complete -c youtube-dl -s t -l title -l id -s A
complete -c youtube-dl -l auto-number -d 'Remove the latter if any.  Do I always have to pass -citw?'
complete -c youtube-dl -l dump-user-agent -d 'You can also get necessary cookies and HTTP headers from JSON output obtained…'
complete -c youtube-dl -l source-address -d 'Also you may need to pass a User-Agent HTTP header of your browser with --use…'
complete -c youtube-dl -l cookies
complete -c youtube-dl -l hls-prefer-ffmpeg -d 'subset of videos will fail to download correctly'

