# extend = "./default.toml"

[lint]
select = [ "ALL" ]
ignore = [
    "D203", "D213", # They conflict with D211 and D212
    "D413", "D407", "D406", "D401", # Unnecessary docstring recommendations
    "ANN101", "D107", # self annotation, self docstring
    "I001", "FA102", # Strange errors
    "F841", "F401", # Unused variable and import
    "COM812", "ISC001", # Are deleted on formatting
    "T201", # print statement
    "TD", # style for todo
    "UP015", # not include mode for file opening when reading
]
